#ifndef __RE_RENDERER_SETTINGS_GUI_GRAPHICS_PIPELINES_H__
#define __RE_RENDERER_SETTINGS_GUI_GRAPHICS_PIPELINES_H__

#include "RE_Renderer_SettingsGUI_Internal.hpp"

namespace RE {



}

#endif /* __RE_RENDERER_SETTINGS_GUI_GRAPHICS_PIPELINES_H__ */
