#ifndef __RE_VULKAN_DEVICE_H__
#define __RE_VULKAN_DEVICE_H__

#include "RE_Vulkan_Instance.hpp"

namespace RE {

	extern VkDevice vk_hDevice;

	// Vulkan 1.0
	extern PFN_vkGetDeviceQueue pfn_vkGetDeviceQueue;
	extern PFN_vkQueueSubmit pfn_vkQueueSubmit;
	extern PFN_vkQueueWaitIdle pfn_vkQueueWaitIdle;
	extern PFN_vkDeviceWaitIdle pfn_vkDeviceWaitIdle;
	extern PFN_vkAllocateMemory pfn_vkAllocateMemory;
	extern PFN_vkFreeMemory pfn_vkFreeMemory;
	extern PFN_vkMapMemory pfn_vkMapMemory;
	extern PFN_vkUnmapMemory pfn_vkUnmapMemory;
	extern PFN_vkFlushMappedMemoryRanges pfn_vkFlushMappedMemoryRanges;
	extern PFN_vkInvalidateMappedMemoryRanges pfn_vkInvalidateMappedMemoryRanges;
	extern PFN_vkGetDeviceMemoryCommitment pfn_vkGetDeviceMemoryCommitment;
	extern PFN_vkBindBufferMemory pfn_vkBindBufferMemory;
	extern PFN_vkBindImageMemory pfn_vkBindImageMemory;
	extern PFN_vkGetBufferMemoryRequirements pfn_vkGetBufferMemoryRequirements;
	extern PFN_vkGetImageMemoryRequirements pfn_vkGetImageMemoryRequirements;
	extern PFN_vkGetImageSparseMemoryRequirements pfn_vkGetImageSparseMemoryRequirements;
	extern PFN_vkQueueBindSparse pfn_vkQueueBindSparse;
	extern PFN_vkCreateFence pfn_vkCreateFence;
	extern PFN_vkDestroyFence pfn_vkDestroyFence;
	extern PFN_vkResetFences pfn_vkResetFences;
	extern PFN_vkGetFenceStatus pfn_vkGetFenceStatus;
	extern PFN_vkWaitForFences pfn_vkWaitForFences;
	extern PFN_vkCreateSemaphore pfn_vkCreateSemaphore;
	extern PFN_vkDestroySemaphore pfn_vkDestroySemaphore;
	extern PFN_vkCreateEvent pfn_vkCreateEvent;
	extern PFN_vkDestroyEvent pfn_vkDestroyEvent;
	extern PFN_vkGetEventStatus pfn_vkGetEventStatus;
	extern PFN_vkSetEvent pfn_vkSetEvent;
	extern PFN_vkResetEvent pfn_vkResetEvent;
	extern PFN_vkCreateQueryPool pfn_vkCreateQueryPool;
	extern PFN_vkDestroyQueryPool pfn_vkDestroyQueryPool;
	extern PFN_vkGetQueryPoolResults pfn_vkGetQueryPoolResults;
	extern PFN_vkCreateBuffer pfn_vkCreateBuffer;
	extern PFN_vkDestroyBuffer pfn_vkDestroyBuffer;
	extern PFN_vkCreateBufferView pfn_vkCreateBufferView;
	extern PFN_vkDestroyBufferView pfn_vkDestroyBufferView;	
	extern PFN_vkCreateImage pfn_vkCreateImage;
	extern PFN_vkDestroyImage pfn_vkDestroyImage;
	extern PFN_vkGetImageSubresourceLayout pfn_vkGetImageSubresourceLayout;
	extern PFN_vkCreateImageView pfn_vkCreateImageView;
	extern PFN_vkDestroyImageView pfn_vkDestroyImageView;
	extern PFN_vkCreateShaderModule pfn_vkCreateShaderModule;
	extern PFN_vkDestroyShaderModule pfn_vkDestroyShaderModule;
	extern PFN_vkCreatePipelineCache pfn_vkCreatePipelineCache;
	extern PFN_vkDestroyPipelineCache pfn_vkDestroyPipelineCache;
	extern PFN_vkGetPipelineCacheData pfn_vkGetPipelineCacheData;
	extern PFN_vkMergePipelineCaches pfn_vkMergePipelineCaches;
	extern PFN_vkCreateGraphicsPipelines pfn_vkCreateGraphicsPipelines;
	extern PFN_vkCreateComputePipelines pfn_vkCreateComputePipelines;
	extern PFN_vkDestroyPipeline pfn_vkDestroyPipeline;
	extern PFN_vkCreatePipelineLayout pfn_vkCreatePipelineLayout;
	extern PFN_vkDestroyPipelineLayout pfn_vkDestroyPipelineLayout;
	extern PFN_vkCreateSampler pfn_vkCreateSampler;
	extern PFN_vkDestroySampler pfn_vkDestroySampler;
	extern PFN_vkCreateDescriptorSetLayout pfn_vkCreateDescriptorSetLayout;
	extern PFN_vkDestroyDescriptorSetLayout pfn_vkDestroyDescriptorSetLayout;
	extern PFN_vkCreateDescriptorPool pfn_vkCreateDescriptorPool;
	extern PFN_vkDestroyDescriptorPool pfn_vkDestroyDescriptorPool;
	extern PFN_vkResetDescriptorPool pfn_vkResetDescriptorPool;
	extern PFN_vkAllocateDescriptorSets pfn_vkAllocateDescriptorSets;
	extern PFN_vkFreeDescriptorSets pfn_vkFreeDescriptorSets;
	extern PFN_vkUpdateDescriptorSets pfn_vkUpdateDescriptorSets;
	extern PFN_vkCreateFramebuffer pfn_vkCreateFramebuffer;
	extern PFN_vkDestroyFramebuffer pfn_vkDestroyFramebuffer;
	extern PFN_vkCreateRenderPass pfn_vkCreateRenderPass;
	extern PFN_vkDestroyRenderPass pfn_vkDestroyRenderPass;
	extern PFN_vkGetRenderAreaGranularity pfn_vkGetRenderAreaGranularity;
	extern PFN_vkCreateCommandPool pfn_vkCreateCommandPool;
	extern PFN_vkDestroyCommandPool pfn_vkDestroyCommandPool;
	extern PFN_vkResetCommandPool pfn_vkResetCommandPool;
	extern PFN_vkAllocateCommandBuffers pfn_vkAllocateCommandBuffers;
	extern PFN_vkFreeCommandBuffers pfn_vkFreeCommandBuffers;
	extern PFN_vkBeginCommandBuffer pfn_vkBeginCommandBuffer;
	extern PFN_vkEndCommandBuffer pfn_vkEndCommandBuffer;
	extern PFN_vkResetCommandBuffer pfn_vkResetCommandBuffer;
	extern PFN_vkCmdBindPipeline pfn_vkCmdBindPipeline;
	extern PFN_vkCmdSetViewport pfn_vkCmdSetViewport;
	extern PFN_vkCmdSetScissor pfn_vkCmdSetScissor;
	extern PFN_vkCmdSetLineWidth pfn_vkCmdSetLineWidth;
	extern PFN_vkCmdSetDepthBias pfn_vkCmdSetDepthBias;
	extern PFN_vkCmdSetBlendConstants pfn_vkCmdSetBlendConstants;
	extern PFN_vkCmdSetDepthBounds pfn_vkCmdSetDepthBounds;
	extern PFN_vkCmdSetStencilCompareMask pfn_vkCmdSetStencilCompareMask;
	extern PFN_vkCmdSetStencilWriteMask pfn_vkCmdSetStencilWriteMask;
	extern PFN_vkCmdSetStencilReference pfn_vkCmdSetStencilReference;
	extern PFN_vkCmdBindDescriptorSets pfn_vkCmdBindDescriptorSets;
	extern PFN_vkCmdBindIndexBuffer pfn_vkCmdBindIndexBuffer;
	extern PFN_vkCmdBindVertexBuffers pfn_vkCmdBindVertexBuffers;
	extern PFN_vkCmdDraw pfn_vkCmdDraw;
	extern PFN_vkCmdDrawIndexed pfn_vkCmdDrawIndexed;
	extern PFN_vkCmdDrawIndirect pfn_vkCmdDrawIndirect;
	extern PFN_vkCmdDrawIndexedIndirect pfn_vkCmdDrawIndexedIndirect;
	extern PFN_vkCmdDispatch pfn_vkCmdDispatch;
	extern PFN_vkCmdDispatchIndirect pfn_vkCmdDispatchIndirect;
	extern PFN_vkCmdCopyBuffer pfn_vkCmdCopyBuffer;
	extern PFN_vkCmdCopyImage pfn_vkCmdCopyImage;
	extern PFN_vkCmdBlitImage pfn_vkCmdBlitImage;
	extern PFN_vkCmdCopyBufferToImage pfn_vkCmdCopyBufferToImage;
	extern PFN_vkCmdCopyImageToBuffer pfn_vkCmdCopyImageToBuffer;
	extern PFN_vkCmdUpdateBuffer pfn_vkCmdUpdateBuffer;
	extern PFN_vkCmdFillBuffer pfn_vkCmdFillBuffer;
	extern PFN_vkCmdClearColorImage pfn_vkCmdClearColorImage;
	extern PFN_vkCmdClearDepthStencilImage pfn_vkCmdClearDepthStencilImage;
	extern PFN_vkCmdClearAttachments pfn_vkCmdClearAttachments;
	extern PFN_vkCmdResolveImage pfn_vkCmdResolveImage;
	extern PFN_vkCmdSetEvent pfn_vkCmdSetEvent;
	extern PFN_vkCmdResetEvent pfn_vkCmdResetEvent;
	extern PFN_vkCmdWaitEvents pfn_vkCmdWaitEvents;
	extern PFN_vkCmdPipelineBarrier pfn_vkCmdPipelineBarrier;
	extern PFN_vkCmdBeginQuery pfn_vkCmdBeginQuery;
	extern PFN_vkCmdEndQuery pfn_vkCmdEndQuery;
	extern PFN_vkCmdResetQueryPool pfn_vkCmdResetQueryPool;
	extern PFN_vkCmdWriteTimestamp pfn_vkCmdWriteTimestamp;
	extern PFN_vkCmdCopyQueryPoolResults pfn_vkCmdCopyQueryPoolResults;
	extern PFN_vkCmdPushConstants pfn_vkCmdPushConstants;
	extern PFN_vkCmdBeginRenderPass pfn_vkCmdBeginRenderPass;
	extern PFN_vkCmdNextSubpass pfn_vkCmdNextSubpass;
	extern PFN_vkCmdEndRenderPass pfn_vkCmdEndRenderPass;
	extern PFN_vkCmdExecuteCommands pfn_vkCmdExecuteCommands;

	// Vulkan 1.1
	extern PFN_vkBindBufferMemory2 pfn_vkBindBufferMemory2;
	extern PFN_vkBindImageMemory2 pfn_vkBindImageMemory2;
	extern PFN_vkGetDeviceGroupPeerMemoryFeatures pfn_vkGetDeviceGroupPeerMemoryFeatures;
	extern PFN_vkCmdSetDeviceMask pfn_vkCmdSetDeviceMask;
	extern PFN_vkCmdDispatchBase pfn_vkCmdDispatchBase;
	extern PFN_vkGetImageMemoryRequirements2 pfn_vkGetImageMemoryRequirements2;
	extern PFN_vkGetBufferMemoryRequirements2 pfn_vkGetBufferMemoryRequirements2;
	extern PFN_vkGetImageSparseMemoryRequirements2 pfn_vkGetImageSparseMemoryRequirements2;
	extern PFN_vkTrimCommandPool pfn_vkTrimCommandPool;
	extern PFN_vkGetDeviceQueue2 pfn_vkGetDeviceQueue2;
	extern PFN_vkCreateSamplerYcbcrConversion pfn_vkCreateSamplerYcbcrConversion;
	extern PFN_vkDestroySamplerYcbcrConversion pfn_vkDestroySamplerYcbcrConversion;
	extern PFN_vkCreateDescriptorUpdateTemplate pfn_vkCreateDescriptorUpdateTemplate;
	extern PFN_vkDestroyDescriptorUpdateTemplate pfn_vkDestroyDescriptorUpdateTemplate;
	extern PFN_vkUpdateDescriptorSetWithTemplate pfn_vkUpdateDescriptorSetWithTemplate;
	extern PFN_vkGetDescriptorSetLayoutSupport pfn_vkGetDescriptorSetLayoutSupport;

	// Vulkan 1.2
	extern PFN_vkCmdDrawIndirectCount pfn_vkCmdDrawIndirectCount;
	extern PFN_vkCmdDrawIndexedIndirectCount pfn_vkCmdDrawIndexedIndirectCount;
	extern PFN_vkCreateRenderPass2 pfn_vkCreateRenderPass2;
	extern PFN_vkCmdBeginRenderPass2 pfn_vkCmdBeginRenderPass2;
	extern PFN_vkCmdNextSubpass2 pfn_vkCmdNextSubpass2;
	extern PFN_vkCmdEndRenderPass2 pfn_vkCmdEndRenderPass2;
	extern PFN_vkResetQueryPool pfn_vkResetQueryPool;
	extern PFN_vkGetSemaphoreCounterValue pfn_vkGetSemaphoreCounterValue;
	extern PFN_vkWaitSemaphores pfn_vkWaitSemaphores;
	extern PFN_vkSignalSemaphore pfn_vkSignalSemaphore;
	extern PFN_vkGetBufferDeviceAddress pfn_vkGetBufferDeviceAddress;
	extern PFN_vkGetBufferOpaqueCaptureAddress pfn_vkGetBufferOpaqueCaptureAddress;
	extern PFN_vkGetDeviceMemoryOpaqueCaptureAddress pfn_vkGetDeviceMemoryOpaqueCaptureAddress;

	// Vulkan 1.3
	extern PFN_vkCreatePrivateDataSlot pfn_vkCreatePrivateDataSlot;
	extern PFN_vkDestroyPrivateDataSlot pfn_vkDestroyPrivateDataSlot;
	extern PFN_vkSetPrivateData pfn_vkSetPrivateData;
	extern PFN_vkGetPrivateData pfn_vkGetPrivateData;
	extern PFN_vkCmdSetEvent2 pfn_vkCmdSetEvent2;
	extern PFN_vkCmdResetEvent2 pfn_vkCmdResetEvent2;
	extern PFN_vkCmdWaitEvents2 pfn_vkCmdWaitEvents2;
	extern PFN_vkCmdPipelineBarrier2 pfn_vkCmdPipelineBarrier2;
	extern PFN_vkCmdWriteTimestamp2 pfn_vkCmdWriteTimestamp2;
	extern PFN_vkQueueSubmit2 pfn_vkQueueSubmit2;
	extern PFN_vkCmdCopyBuffer2 pfn_vkCmdCopyBuffer2;
	extern PFN_vkCmdCopyImage2 pfn_vkCmdCopyImage2;
	extern PFN_vkCmdCopyBufferToImage2 pfn_vkCmdCopyBufferToImage2;
	extern PFN_vkCmdCopyImageToBuffer2 pfn_vkCmdCopyImageToBuffer2;
	extern PFN_vkCmdBlitImage2 pfn_vkCmdBlitImage2;
	extern PFN_vkCmdResolveImage2 pfn_vkCmdResolveImage2;
	extern PFN_vkCmdBeginRendering pfn_vkCmdBeginRendering;
	extern PFN_vkCmdEndRendering pfn_vkCmdEndRendering;
	extern PFN_vkCmdSetCullMode pfn_vkCmdSetCullMode;
	extern PFN_vkCmdSetFrontFace pfn_vkCmdSetFrontFace;
	extern PFN_vkCmdSetPrimitiveTopology pfn_vkCmdSetPrimitiveTopology;
	extern PFN_vkCmdSetViewportWithCount pfn_vkCmdSetViewportWithCount;
	extern PFN_vkCmdSetScissorWithCount pfn_vkCmdSetScissorWithCount;
	extern PFN_vkCmdBindVertexBuffers2 pfn_vkCmdBindVertexBuffers2;
	extern PFN_vkCmdSetDepthTestEnable pfn_vkCmdSetDepthTestEnable;
	extern PFN_vkCmdSetDepthWriteEnable pfn_vkCmdSetDepthWriteEnable;
	extern PFN_vkCmdSetDepthCompareOp pfn_vkCmdSetDepthCompareOp;
	extern PFN_vkCmdSetDepthBoundsTestEnable pfn_vkCmdSetDepthBoundsTestEnable;
	extern PFN_vkCmdSetStencilTestEnable pfn_vkCmdSetStencilTestEnable;
	extern PFN_vkCmdSetStencilOp pfn_vkCmdSetStencilOp;
	extern PFN_vkCmdSetRasterizerDiscardEnable pfn_vkCmdSetRasterizerDiscardEnable;
	extern PFN_vkCmdSetDepthBiasEnable pfn_vkCmdSetDepthBiasEnable;
	extern PFN_vkCmdSetPrimitiveRestartEnable pfn_vkCmdSetPrimitiveRestartEnable;
	extern PFN_vkGetDeviceBufferMemoryRequirements pfn_vkGetDeviceBufferMemoryRequirements;
	extern PFN_vkGetDeviceImageMemoryRequirements pfn_vkGetDeviceImageMemoryRequirements;
	extern PFN_vkGetDeviceImageSparseMemoryRequirements pfn_vkGetDeviceImageSparseMemoryRequirements;

	// Vulkan 1.4
	/* extern PFN_vkCmdSetLineStipple pfn_vkCmdSetLineStipple;
	extern PFN_vkMapMemory2 pfn_vkMapMemory2;
	extern PFN_vkUnmapMemory2 pfn_vkUnmapMemory2;
	extern PFN_vkCmdBindIndexBuffer2 pfn_vkCmdBindIndexBuffer2;
	extern PFN_vkGetRenderingAreaGranularity pfn_vkGetRenderingAreaGranularity;
	extern PFN_vkGetDeviceImageSubresourceLayout pfn_vkGetDeviceImageSubresourceLayout;
	extern PFN_vkGetImageSubresourceLayout2 pfn_vkGetImageSubresourceLayout2;
	extern PFN_vkCmdPushDescriptorSet pfn_vkCmdPushDescriptorSet;
	extern PFN_vkCmdPushDescriptorSetWithTemplate pfn_vkCmdPushDescriptorSetWithTemplate;
	extern PFN_vkCmdSetRenderingAttachmentLocations pfn_vkCmdSetRenderingAttachmentLocations;
	extern PFN_vkCmdSetRenderingInputAttachmentIndices pfn_vkCmdSetRenderingInputAttachmentIndices;
	extern PFN_vkCmdBindDescriptorSets2 pfn_vkCmdBindDescriptorSets2;
	extern PFN_vkCmdPushConstants2 pfn_vkCmdPushConstants2;
	extern PFN_vkCmdPushDescriptorSet2 pfn_vkCmdPushDescriptorSet2;
	extern PFN_vkCmdPushDescriptorSetWithTemplate2 pfn_vkCmdPushDescriptorSetWithTemplate2;
	extern PFN_vkCopyMemoryToImage pfn_vkCopyMemoryToImage;
	extern PFN_vkCopyImageToMemory pfn_vkCopyImageToMemory;
	extern PFN_vkCopyImageToImage pfn_vkCopyImageToImage;
	extern PFN_vkTransitionImageLayout pfn_vkTransitionImageLayout; */

	bool init_logical_vulkan_device();
	void destroy_logical_vulkan_device();

// Vulkan 1.0
#define vkGetDeviceQueue(...) pfn_vkGetDeviceQueue(__VA_ARGS__)
#define vkQueueSubmit(...) pfn_vkQueueSubmit(__VA_ARGS__)
#define vkQueueWaitIdle(...) pfn_vkQueueWaitIdle(__VA_ARGS__)
#define vkDeviceWaitIdle(...) pfn_vkDeviceWaitIdle(__VA_ARGS__)
#define vkAllocateMemory(...) pfn_vkAllocateMemory(__VA_ARGS__)
#define vkFreeMemory(...) pfn_vkFreeMemory(__VA_ARGS__)
#define vkMapMemory(...) pfn_vkMapMemory(__VA_ARGS__)
#define vkUnmapMemory(...) pfn_vkUnmapMemory(__VA_ARGS__)
#define vkFlushMappedMemoryRanges(...) pfn_vkFlushMappedMemoryRanges(__VA_ARGS__)
#define vkInvalidateMappedMemoryRanges(...) pfn_vkInvalidateMappedMemoryRanges(__VA_ARGS__)
#define vkGetDeviceMemoryCommitment(...) pfn_vkGetDeviceMemoryCommitment(__VA_ARGS__)
#define vkBindBufferMemory(...) pfn_vkBindBufferMemory(__VA_ARGS__)
#define vkBindImageMemory(...) pfn_vkBindImageMemory(__VA_ARGS__)
#define vkGetBufferMemoryRequirements(...) pfn_vkGetBufferMemoryRequirements(__VA_ARGS__)
#define vkGetImageMemoryRequirements(...) pfn_vkGetImageMemoryRequirements(__VA_ARGS__)
#define vkGetImageSparseMemoryRequirements(...) pfn_vkGetImageSparseMemoryRequirements(__VA_ARGS__)
#define vkQueueBindSparse(...) pfn_vkQueueBindSparse(__VA_ARGS__)
#define vkCreateFence(...) pfn_vkCreateFence(__VA_ARGS__)
#define vkDestroyFence(...) pfn_vkDestroyFence(__VA_ARGS__)
#define vkResetFences(...) pfn_vkResetFences(__VA_ARGS__)
#define vkGetFenceStatus(...) pfn_vkGetFenceStatus(__VA_ARGS__)
#define vkWaitForFences(...) pfn_vkWaitForFences(__VA_ARGS__)
#define vkCreateSemaphore(...) pfn_vkCreateSemaphore(__VA_ARGS__)
#define vkDestroySemaphore(...) pfn_vkDestroySemaphore(__VA_ARGS__)
#define vkCreateEvent(...) pfn_vkCreateEvent(__VA_ARGS__)
#define vkDestroyEvent(...) pfn_vkDestroyEvent(__VA_ARGS__)
#define vkGetEventStatus(...) pfn_vkGetEventStatus(__VA_ARGS__)
#define vkSetEvent(...) pfn_vkSetEvent(__VA_ARGS__)
#define vkResetEvent(...) pfn_vkResetEvent(__VA_ARGS__)
#define vkCreateQueryPool(...) pfn_vkCreateQueryPool(__VA_ARGS__)
#define vkDestroyQueryPool(...) pfn_vkDestroyQueryPool(__VA_ARGS__)
#define vkGetQueryPoolResults(...) pfn_vkGetQueryPoolResults(__VA_ARGS__)
#define vkCreateBuffer(...) pfn_vkCreateBuffer(__VA_ARGS__)
#define vkDestroyBuffer(...) pfn_vkDestroyBuffer(__VA_ARGS__)
#define vkCreateBufferView(...) pfn_vkCreateBufferView(__VA_ARGS__)
#define vkDestroyBufferView(...) pfn_vkDestroyBufferView(__VA_ARGS__)
#define vkCreateImage(...) pfn_vkCreateImage(__VA_ARGS__)
#define vkDestroyImage(...) pfn_vkDestroyImage(__VA_ARGS__)
#define vkGetImageSubresourceLayout(...) pfn_vkGetImageSubresourceLayout(__VA_ARGS__)
#define vkCreateImageView(...) pfn_vkCreateImageView(__VA_ARGS__)
#define vkDestroyImageView(...) pfn_vkDestroyImageView(__VA_ARGS__)
#define vkCreateShaderModule(...) pfn_vkCreateShaderModule(__VA_ARGS__)
#define vkDestroyShaderModule(...) pfn_vkDestroyShaderModule(__VA_ARGS__)
#define vkCreatePipelineCache(...) pfn_vkCreatePipelineCache(__VA_ARGS__)
#define vkDestroyPipelineCache(...) pfn_vkDestroyPipelineCache(__VA_ARGS__)
#define vkGetPipelineCacheData(...) pfn_vkGetPipelineCacheData(__VA_ARGS__)
#define vkMergePipelineCaches(...) pfn_vkMergePipelineCaches(__VA_ARGS__)
#define vkCreateGraphicsPipelines(...) pfn_vkCreateGraphicsPipelines(__VA_ARGS__)
#define vkCreateComputePipelines(...) pfn_vkCreateComputePipelines(__VA_ARGS__)
#define vkDestroyPipeline(...) pfn_vkDestroyPipeline(__VA_ARGS__)
#define vkCreatePipelineLayout(...) pfn_vkCreatePipelineLayout(__VA_ARGS__)
#define vkDestroyPipelineLayout(...) pfn_vkDestroyPipelineLayout(__VA_ARGS__)
#define vkCreateSampler(...) pfn_vkCreateSampler(__VA_ARGS__)
#define vkDestroySampler(...) pfn_vkDestroySampler(__VA_ARGS__)
#define vkCreateDescriptorSetLayout(...) pfn_vkCreateDescriptorSetLayout(__VA_ARGS__)
#define vkDestroyDescriptorSetLayout(...) pfn_vkDestroyDescriptorSetLayout(__VA_ARGS__)
#define vkCreateDescriptorPool(...) pfn_vkCreateDescriptorPool(__VA_ARGS__)
#define vkDestroyDescriptorPool(...) pfn_vkDestroyDescriptorPool(__VA_ARGS__)
#define vkResetDescriptorPool(...) pfn_vkResetDescriptorPool(__VA_ARGS__)
#define vkAllocateDescriptorSets(...) pfn_vkAllocateDescriptorSets(__VA_ARGS__)
#define vkFreeDescriptorSets(...) pfn_vkFreeDescriptorSets(__VA_ARGS__)
#define vkUpdateDescriptorSets(...) pfn_vkUpdateDescriptorSets(__VA_ARGS__)
#define vkCreateFramebuffer(...) pfn_vkCreateFramebuffer(__VA_ARGS__)
#define vkDestroyFramebuffer(...) pfn_vkDestroyFramebuffer(__VA_ARGS__)
#define vkCreateRenderPass(...) pfn_vkCreateRenderPass(__VA_ARGS__)
#define vkDestroyRenderPass(...) pfn_vkDestroyRenderPass(__VA_ARGS__)
#define vkGetRenderAreaGranularity(...) pfn_vkGetRenderAreaGranularity(__VA_ARGS__)
#define vkCreateCommandPool(...) pfn_vkCreateCommandPool(__VA_ARGS__)
#define vkDestroyCommandPool(...) pfn_vkDestroyCommandPool(__VA_ARGS__)
#define vkResetCommandPool(...) pfn_vkResetCommandPool(__VA_ARGS__)
#define vkAllocateCommandBuffers(...) pfn_vkAllocateCommandBuffers(__VA_ARGS__)
#define vkFreeCommandBuffers(...) pfn_vkFreeCommandBuffers(__VA_ARGS__)
#define vkBeginCommandBuffer(...) pfn_vkBeginCommandBuffer(__VA_ARGS__)
#define vkEndCommandBuffer(...) pfn_vkEndCommandBuffer(__VA_ARGS__)
#define vkResetCommandBuffer(...) pfn_vkResetCommandBuffer(__VA_ARGS__)
#define vkCmdBindPipeline(...) pfn_vkCmdBindPipeline(__VA_ARGS__)
#define vkCmdSetViewport(...) pfn_vkCmdSetViewport(__VA_ARGS__)
#define vkCmdSetScissor(...) pfn_vkCmdSetScissor(__VA_ARGS__)
#define vkCmdSetLineWidth(...) pfn_vkCmdSetLineWidth(__VA_ARGS__)
#define vkCmdSetDepthBias(...) pfn_vkCmdSetDepthBias(__VA_ARGS__)
#define vkCmdSetBlendConstants(...) pfn_vkCmdSetBlendConstants(__VA_ARGS__)
#define vkCmdSetDepthBounds(...) pfn_vkCmdSetDepthBounds(__VA_ARGS__)
#define vkCmdSetStencilCompareMask(...) pfn_vkCmdSetStencilCompareMask(__VA_ARGS__)
#define vkCmdSetStencilWriteMask(...) pfn_vkCmdSetStencilWriteMask(__VA_ARGS__)
#define vkCmdSetStencilReference(...) pfn_vkCmdSetStencilReference(__VA_ARGS__)
#define vkCmdBindDescriptorSets(...) pfn_vkCmdBindDescriptorSets(__VA_ARGS__)
#define vkCmdBindIndexBuffer(...) pfn_vkCmdBindIndexBuffer(__VA_ARGS__)
#define vkCmdBindVertexBuffers(...) pfn_vkCmdBindVertexBuffers(__VA_ARGS__)
#define vkCmdDraw(...) pfn_vkCmdDraw(__VA_ARGS__)
#define vkCmdDrawIndexed(...) pfn_vkCmdDrawIndexed(__VA_ARGS__)
#define vkCmdDrawIndirect(...) pfn_vkCmdDrawIndirect(__VA_ARGS__)
#define vkCmdDrawIndexedIndirect(...) pfn_vkCmdDrawIndexedIndirect(__VA_ARGS__)
#define vkCmdDispatch(...) pfn_vkCmdDispatch(__VA_ARGS__)
#define vkCmdDispatchIndirect(...) pfn_vkCmdDispatchIndirect(__VA_ARGS__)
#define vkCmdCopyBuffer(...) pfn_vkCmdCopyBuffer(__VA_ARGS__)
#define vkCmdCopyImage(...) pfn_vkCmdCopyImage(__VA_ARGS__)
#define vkCmdBlitImage(...) pfn_vkCmdBlitImage(__VA_ARGS__)
#define vkCmdCopyBufferToImage(...) pfn_vkCmdCopyBufferToImage(__VA_ARGS__)
#define vkCmdCopyImageToBuffer(...) pfn_vkCmdCopyImageToBuffer(__VA_ARGS__)
#define vkCmdUpdateBuffer(...) pfn_vkCmdUpdateBuffer(__VA_ARGS__)
#define vkCmdFillBuffer(...) pfn_vkCmdFillBuffer(__VA_ARGS__)
#define vkCmdClearColorImage(...) pfn_vkCmdClearColorImage(__VA_ARGS__)
#define vkCmdClearDepthStencilImage(...) pfn_vkCmdClearDepthStencilImage(__VA_ARGS__)
#define vkCmdClearAttachments(...) pfn_vkCmdClearAttachments(__VA_ARGS__)
#define vkCmdResolveImage(...) pfn_vkCmdResolveImage(__VA_ARGS__)
#define vkCmdSetEvent(...) pfn_vkCmdSetEvent(__VA_ARGS__)
#define vkCmdResetEvent(...) pfn_vkCmdResetEvent(__VA_ARGS__)
#define vkCmdWaitEvents(...) pfn_vkCmdWaitEvents(__VA_ARGS__)
#define vkCmdPipelineBarrier(...) pfn_vkCmdPipelineBarrier(__VA_ARGS__)
#define vkCmdBeginQuery(...) pfn_vkCmdBeginQuery(__VA_ARGS__)
#define vkCmdEndQuery(...) pfn_vkCmdEndQuery(__VA_ARGS__)
#define vkCmdResetQueryPool(...) pfn_vkCmdResetQueryPool(__VA_ARGS__)
#define vkCmdWriteTimestamp(...) pfn_vkCmdWriteTimestamp(__VA_ARGS__)
#define vkCmdCopyQueryPoolResults(...) pfn_vkCmdCopyQueryPoolResults(__VA_ARGS__)
#define vkCmdPushConstants(...) pfn_vkCmdPushConstants(__VA_ARGS__)
#define vkCmdBeginRenderPass(...) pfn_vkCmdBeginRenderPass(__VA_ARGS__)
#define vkCmdNextSubpass(...) pfn_vkCmdNextSubpass(__VA_ARGS__)
#define vkCmdEndRenderPass(...) pfn_vkCmdEndRenderPass(__VA_ARGS__)
#define vkCmdExecuteCommands(...) pfn_vkCmdExecuteCommands(__VA_ARGS__)

// Vulkan 1.1
#define vkBindBufferMemory2(...) pfn_vkBindBufferMemory2(__VA_ARGS__)
#define vkBindImageMemory2(...) pfn_vkBindImageMemory2(__VA_ARGS__)
#define vkGetDeviceGroupPeerMemoryFeatures(...) pfn_vkGetDeviceGroupPeerMemoryFeatures(__VA_ARGS__)
#define vkCmdSetDeviceMask(...) pfn_vkCmdSetDeviceMask(__VA_ARGS__)
#define vkCmdDispatchBase(...) pfn_vkCmdDispatchBase(__VA_ARGS__)
#define vkGetImageMemoryRequirements2(...) pfn_vkGetImageMemoryRequirements2(__VA_ARGS__)
#define vkGetBufferMemoryRequirements2(...) pfn_vkGetBufferMemoryRequirements2(__VA_ARGS__)
#define vkGetImageSparseMemoryRequirements2(...) pfn_vkGetImageSparseMemoryRequirements2(__VA_ARGS__)
#define vkTrimCommandPool(...) pfn_vkTrimCommandPool(__VA_ARGS__)
#define vkGetDeviceQueue2(...) pfn_vkGetDeviceQueue2(__VA_ARGS__)
#define vkCreateSamplerYcbcrConversion(...) pfn_vkCreateSamplerYcbcrConversion(__VA_ARGS__)
#define vkDestroySamplerYcbcrConversion(...) pfn_vkDestroySamplerYcbcrConversion(__VA_ARGS__)
#define vkCreateDescriptorUpdateTemplate(...) pfn_vkCreateDescriptorUpdateTemplate(__VA_ARGS__)
#define vkDestroyDescriptorUpdateTemplate(...) pfn_vkDestroyDescriptorUpdateTemplate(__VA_ARGS__)
#define vkUpdateDescriptorSetWithTemplate(...) pfn_vkUpdateDescriptorSetWithTemplate(__VA_ARGS__)
#define vkGetDescriptorSetLayoutSupport(...) pfn_vkGetDescriptorSetLayoutSupport(__VA_ARGS__)

// Vulkan 1.2
#define vkCmdDrawIndirectCount(...) pfn_vkCmdDrawIndirectCount(__VA_ARGS__)
#define vkCmdDrawIndexedIndirectCount(...) pfn_vkCmdDrawIndexedIndirectCount(__VA_ARGS__)
#define vkCreateRenderPass2(...) pfn_vkCreateRenderPass2(__VA_ARGS__)
#define vkCmdBeginRenderPass2(...) pfn_vkCmdBeginRenderPass2(__VA_ARGS__)
#define vkCmdNextSubpass2(...) pfn_vkCmdNextSubpass2(__VA_ARGS__)
#define vkCmdEndRenderPass2(...) pfn_vkCmdEndRenderPass2(__VA_ARGS__)
#define vkResetQueryPool(...) pfn_vkResetQueryPool(__VA_ARGS__)
#define vkGetSemaphoreCounterValue(...) pfn_vkGetSemaphoreCounterValue(__VA_ARGS__)
#define vkWaitSemaphores(...) pfn_vkWaitSemaphores(__VA_ARGS__)
#define vkSignalSemaphore(...) pfn_vkSignalSemaphore(__VA_ARGS__)
#define vkGetBufferDeviceAddress(...) pfn_vkGetBufferDeviceAddress(__VA_ARGS__)
#define vkGetBufferOpaqueCaptureAddress(...) pfn_vkGetBufferOpaqueCaptureAddress(__VA_ARGS__)
#define vkGetDeviceMemoryOpaqueCaptureAddress(...) pfn_vkGetDeviceMemoryOpaqueCaptureAddress(__VA_ARGS__)

// Vulkan 1.3
#define vkCreatePrivateDataSlot(...) pfn_vkCreatePrivateDataSlot(__VA_ARGS__)
#define vkDestroyPrivateDataSlot(...) pfn_vkDestroyPrivateDataSlot(__VA_ARGS__)
#define vkSetPrivateData(...) pfn_vkSetPrivateData(__VA_ARGS__)
#define vkGetPrivateData(...) pfn_vkGetPrivateData(__VA_ARGS__)
#define vkCmdSetEvent2(...) pfn_vkCmdSetEvent2(__VA_ARGS__)
#define vkCmdResetEvent2(...) pfn_vkCmdResetEvent2(__VA_ARGS__)
#define vkCmdWaitEvents2(...) pfn_vkCmdWaitEvents2(__VA_ARGS__)
#define vkCmdPipelineBarrier2(...) pfn_vkCmdPipelineBarrier2(__VA_ARGS__)
#define vkCmdWriteTimestamp2(...) pfn_vkCmdWriteTimestamp2(__VA_ARGS__)
#define vkQueueSubmit2(...) pfn_vkQueueSubmit2(__VA_ARGS__)
#define vkCmdCopyBuffer2(...) pfn_vkCmdCopyBuffer2(__VA_ARGS__)
#define vkCmdCopyImage2(...) pfn_vkCmdCopyImage2(__VA_ARGS__)
#define vkCmdCopyBufferToImage2(...) pfn_vkCmdCopyBufferToImage2(__VA_ARGS__)
#define vkCmdCopyImageToBuffer2(...) pfn_vkCmdCopyImageToBuffer2(__VA_ARGS__)
#define vkCmdBlitImage2(...) pfn_vkCmdBlitImage2(__VA_ARGS__)
#define vkCmdResolveImage2(...) pfn_vkCmdResolveImage2(__VA_ARGS__)
#define vkCmdBeginRendering(...) pfn_vkCmdBeginRendering(__VA_ARGS__)
#define vkCmdEndRendering(...) pfn_vkCmdEndRendering(__VA_ARGS__)
#define vkCmdSetCullMode(...) pfn_vkCmdSetCullMode(__VA_ARGS__)
#define vkCmdSetFrontFace(...) pfn_vkCmdSetFrontFace(__VA_ARGS__)
#define vkCmdSetPrimitiveTopology(...) pfn_vkCmdSetPrimitiveTopology(__VA_ARGS__)
#define vkCmdSetViewportWithCount(...) pfn_vkCmdSetViewportWithCount(__VA_ARGS__)
#define vkCmdSetScissorWithCount(...) pfn_vkCmdSetScissorWithCount(__VA_ARGS__)
#define vkCmdBindVertexBuffers2(...) pfn_vkCmdBindVertexBuffers2(__VA_ARGS__)
#define vkCmdSetDepthTestEnable(...) pfn_vkCmdSetDepthTestEnable(__VA_ARGS__)
#define vkCmdSetDepthWriteEnable(...) pfn_vkCmdSetDepthWriteEnable(__VA_ARGS__)
#define vkCmdSetDepthCompareOp(...) pfn_vkCmdSetDepthCompareOp(__VA_ARGS__)
#define vkCmdSetDepthBoundsTestEnable(...) pfn_vkCmdSetDepthBoundsTestEnable(__VA_ARGS__)
#define vkCmdSetStencilTestEnable(...) pfn_vkCmdSetStencilTestEnable(__VA_ARGS__)
#define vkCmdSetStencilOp(...) pfn_vkCmdSetStencilOp(__VA_ARGS__)
#define vkCmdSetRasterizerDiscardEnable(...) pfn_vkCmdSetRasterizerDiscardEnable(__VA_ARGS__)
#define vkCmdSetDepthBiasEnable(...) pfn_vkCmdSetDepthBiasEnable(__VA_ARGS__)
#define vkCmdSetPrimitiveRestartEnable(...) pfn_vkCmdSetPrimitiveRestartEnable(__VA_ARGS__)
#define vkGetDeviceBufferMemoryRequirements(...) pfn_vkGetDeviceBufferMemoryRequirements(__VA_ARGS__)
#define vkGetDeviceImageMemoryRequirements(...) pfn_vkGetDeviceImageMemoryRequirements(__VA_ARGS__)
#define vkGetDeviceImageSparseMemoryRequirements(...) pfn_vkGetDeviceImageSparseMemoryRequirements(__VA_ARGS__)

// Vulkan 1.4
#define vkCmdSetLineStipple(...) pfn_vkCmdSetLineStipple(__VA_ARGS__)
#define vkMapMemory2(...) pfn_vkMapMemory2(__VA_ARGS__)
#define vkUnmapMemory2(...) pfn_vkUnmapMemory2(__VA_ARGS__)
#define vkCmdBindIndexBuffer2(...) pfn_vkCmdBindIndexBuffer2(__VA_ARGS__)
#define vkGetRenderingAreaGranularity(...) pfn_vkGetRenderingAreaGranularity(__VA_ARGS__)
#define vkGetDeviceImageSubresourceLayout(...) pfn_vkGetDeviceImageSubresourceLayout(__VA_ARGS__)
#define vkGetImageSubresourceLayout2(...) pfn_vkGetImageSubresourceLayout2(__VA_ARGS__)
#define vkCmdPushDescriptorSet(...) pfn_vkCmdPushDescriptorSet(__VA_ARGS__)
#define vkCmdPushDescriptorSetWithTemplate(...) pfn_vkCmdPushDescriptorSetWithTemplate(__VA_ARGS__)
#define vkCmdSetRenderingAttachmentLocations(...) pfn_vkCmdSetRenderingAttachmentLocations(__VA_ARGS__)
#define vkCmdSetRenderingInputAttachmentIndices(...) pfn_vkCmdSetRenderingInputAttachmentIndices(__VA_ARGS__)
#define vkCmdBindDescriptorSets2(...) pfn_vkCmdBindDescriptorSets2(__VA_ARGS__)
#define vkCmdPushConstants2(...) pfn_vkCmdPushConstants2(__VA_ARGS__)
#define vkCmdPushDescriptorSet2(...) pfn_vkCmdPushDescriptorSet2(__VA_ARGS__)
#define vkCmdPushDescriptorSetWithTemplate2(...) pfn_vkCmdPushDescriptorSetWithTemplate2(__VA_ARGS__)
#define vkCopyMemoryToImage(...) pfn_vkCopyMemoryToImage(__VA_ARGS__)
#define vkCopyImageToMemory(...) pfn_vkCopyImageToMemory(__VA_ARGS__)
#define vkCopyImageToImage(...) pfn_vkCopyImageToImage(__VA_ARGS__)
#define vkTransitionImageLayout(...) pfn_vkTransitionImageLayout(__VA_ARGS__)

// Debug extension
#define vkQueueBeginDebugUtilsLabelEXT(...) pfn_vkQueueBeginDebugUtilsLabelEXT(__VA_ARGS__)
#define vkQueueEndDebugUtilsLabelEXT(...) pfn_vkQueueEndDebugUtilsLabelEXT(__VA_ARGS__)
#define vkQueueInsertDebugUtilsLabelEXT(...) pfn_vkQueueInsertDebugUtilsLabelEXT(__VA_ARGS__)
#define vkCmdBeginDebugUtilsLabelEXT(...) pfn_vkCmdBeginDebugUtilsLabelEXT(__VA_ARGS__)
#define vkCmdEndDebugUtilsLabelEXT(...) pfn_vkCmdEndDebugUtilsLabelEXT(__VA_ARGS__)
#define vkCmdInsertDebugUtilsLabelEXT(...) pfn_vkCmdInsertDebugUtilsLabelEXT(__VA_ARGS__)
// Swapchain extension
#define vkCreateSwapchainKHR(...) pfn_vkCreateSwapchainKHR(__VA_ARGS__)
#define vkDestroySwapchainKHR(...) pfn_vkDestroySwapchainKHR(__VA_ARGS__)
#define vkGetSwapchainImagesKHR(...) pfn_vkGetSwapchainImagesKHR(__VA_ARGS__)
#define vkAcquireNextImageKHR(...) pfn_vkAcquireNextImageKHR(__VA_ARGS__)
#define vkQueuePresentKHR(...) pfn_vkQueuePresentKHR(__VA_ARGS__)
#define vkGetDeviceGroupPresentCapabilitiesKHR(...) pfn_vkGetDeviceGroupPresentCapabilitiesKHR(__VA_ARGS__)
#define vkGetDeviceGroupSurfacePresentModesKHR(...) pfn_vkGetDeviceGroupSurfacePresentModesKHR(__VA_ARGS__)
#define vkAcquireNextImage2KHR(...) pfn_vkAcquireNextImage2KHR(__VA_ARGS__)

#define WAIT_FOR_IDLE_VULKAN_DEVICE() vkDeviceWaitIdle(vk_hDevice)

}

#endif /* __RE_VULKAN_DEVICE_H__ */
