#ifndef __RE_VULKAN_DEVICE_H__
#define __RE_VULKAN_DEVICE_H__

#include "RE_Vulkan_Instance.hpp"

namespace RE {

	extern VkDevice vk_hDevice;

	// Vulkan 1.0
	extern PFN_vkGetDeviceQueue pfn_vkGetDeviceQueue;
	extern PFN_vkQueueSubmit pfn_vkQueueSubmit;
	extern PFN_vkQueueWaitIdle pfn_vkQueueWaitIdle;
	extern PFN_vkDeviceWaitIdle pfn_vkDeviceWaitIdle;
	extern PFN_vkAllocateMemory pfn_vkAllocateMemory;
	extern PFN_vkFreeMemory pfn_vkFreeMemory;
	extern PFN_vkMapMemory pfn_vkMapMemory;
	extern PFN_vkUnmapMemory pfn_vkUnmapMemory;
	extern PFN_vkFlushMappedMemoryRanges pfn_vkFlushMappedMemoryRanges;
	extern PFN_vkInvalidateMappedMemoryRanges pfn_vkInvalidateMappedMemoryRanges;
	extern PFN_vkGetDeviceMemoryCommitment pfn_vkGetDeviceMemoryCommitment;
	extern PFN_vkBindBufferMemory pfn_vkBindBufferMemory;
	extern PFN_vkBindImageMemory pfn_vkBindImageMemory;
	extern PFN_vkGetBufferMemoryRequirements pfn_vkGetBufferMemoryRequirements;
	extern PFN_vkGetImageMemoryRequirements pfn_vkGetImageMemoryRequirements;
	extern PFN_vkGetImageSparseMemoryRequirements pfn_vkGetImageSparseMemoryRequirements;
	extern PFN_vkGetPhysicalDeviceSparseImageFormatProperties pfn_vkGetPhysicalDeviceSparseImageFormatProperties;
	extern PFN_vkQueueBindSparse pfn_vkQueueBindSparse;
	extern PFN_vkCreateFence pfn_vkCreateFence;
	extern PFN_vkDestroyFence pfn_vkDestroyFence;
	extern PFN_vkResetFences pfn_vkResetFences;
	extern PFN_vkGetFenceStatus pfn_vkGetFenceStatus;
	extern PFN_vkWaitForFences pfn_vkWaitForFences;
	extern PFN_vkCreateSemaphore pfn_vkCreateSemaphore;
	extern PFN_vkDestroySemaphore pfn_vkDestroySemaphore;
	extern PFN_vkCreateEvent pfn_vkCreateEvent;
	extern PFN_vkDestroyEvent pfn_vkDestroyEvent;
	extern PFN_vkGetEventStatus pfn_vkGetEventStatus;
	extern PFN_vkSetEvent pfn_vkSetEvent;
	extern PFN_vkResetEvent pfn_vkResetEvent;
	extern PFN_vkCreateQueryPool pfn_vkCreateQueryPool;
	extern PFN_vkDestroyQueryPool pfn_vkDestroyQueryPool;
	extern PFN_vkGetQueryPoolResults pfn_vkGetQueryPoolResults;
	extern PFN_vkCreateBuffer pfn_vkCreateBuffer;
	extern PFN_vkDestroyBuffer pfn_vkDestroyBuffer;
	extern PFN_vkCreateBufferView pfn_vkCreateBufferView;
	extern PFN_vkDestroyBufferView pfn_vkDestroyBufferView;	
	extern PFN_vkCreateImage pfn_vkCreateImage;
	extern PFN_vkDestroyImage pfn_vkDestroyImage;
	extern PFN_vkGetImageSubresourceLayout pfn_vkGetImageSubresourceLayout;
	extern PFN_vkCreateImageView pfn_vkCreateImageView;
	extern PFN_vkDestroyImageView pfn_vkDestroyImageView;
	extern PFN_vkCreateShaderModule pfn_vkCreateShaderModule;
	extern PFN_vkDestroyShaderModule pfn_vkDestroyShaderModule;
	extern PFN_vkCreatePipelineCache pfn_vkCreatePipelineCache;
	extern PFN_vkDestroyPipelineCache pfn_vkDestroyPipelineCache;
	extern PFN_vkGetPipelineCacheData pfn_vkGetPipelineCacheData;
	extern PFN_vkMergePipelineCaches pfn_vkMergePipelineCaches;
	extern PFN_vkCreateGraphicsPipelines pfn_vkCreateGraphicsPipelines;
	extern PFN_vkCreateComputePipelines pfn_vkCreateComputePipelines;
	extern PFN_vkDestroyPipeline pfn_vkDestroyPipeline;
	extern PFN_vkCreatePipelineLayout pfn_vkCreatePipelineLayout;
	extern PFN_vkDestroyPipelineLayout pfn_vkDestroyPipelineLayout;
	extern PFN_vkCreateSampler pfn_vkCreateSampler;
	extern PFN_vkDestroySampler pfn_vkDestroySampler;
	extern PFN_vkCreateDescriptorSetLayout pfn_vkCreateDescriptorSetLayout;
	extern PFN_vkDestroyDescriptorSetLayout pfn_vkDestroyDescriptorSetLayout;
	extern PFN_vkCreateDescriptorPool pfn_vkCreateDescriptorPool;
	extern PFN_vkDestroyDescriptorPool pfn_vkDestroyDescriptorPool;
	extern PFN_vkResetDescriptorPool pfn_vkResetDescriptorPool;
	extern PFN_vkAllocateDescriptorSets pfn_vkAllocateDescriptorSets;
	extern PFN_vkFreeDescriptorSets pfn_vkFreeDescriptorSets;
	extern PFN_vkUpdateDescriptorSets pfn_vkUpdateDescriptorSets;
	extern PFN_vkCreateFramebuffer pfn_vkCreateFramebuffer;
	extern PFN_vkDestroyFramebuffer pfn_vkDestroyFramebuffer;
	extern PFN_vkCreateRenderPass pfn_vkCreateRenderPass;
	extern PFN_vkDestroyRenderPass pfn_vkDestroyRenderPass;
	extern PFN_vkGetRenderAreaGranularity pfn_vkGetRenderAreaGranularity;
	extern PFN_vkCreateCommandPool pfn_vkCreateCommandPool;
	extern PFN_vkDestroyCommandPool pfn_vkDestroyCommandPool;
	extern PFN_vkResetCommandPool pfn_vkResetCommandPool;
	extern PFN_vkAllocateCommandBuffers pfn_vkAllocateCommandBuffers;
	extern PFN_vkFreeCommandBuffers pfn_vkFreeCommandBuffers;
	extern PFN_vkBeginCommandBuffer pfn_vkBeginCommandBuffer;
	extern PFN_vkEndCommandBuffer pfn_vkEndCommandBuffer;
	extern PFN_vkResetCommandBuffer pfn_vkResetCommandBuffer;
	extern PFN_vkCmdBindPipeline pfn_vkCmdBindPipeline;
	extern PFN_vkCmdSetViewport pfn_vkCmdSetViewport;
	extern PFN_vkCmdSetScissor pfn_vkCmdSetScissor;
	extern PFN_vkCmdSetLineWidth pfn_vkCmdSetLineWidth;
	extern PFN_vkCmdSetDepthBias pfn_vkCmdSetDepthBias;
	extern PFN_vkCmdSetBlendConstants pfn_vkCmdSetBlendConstants;
	extern PFN_vkCmdSetDepthBounds pfn_vkCmdSetDepthBounds;
	extern PFN_vkCmdSetStencilCompareMask pfn_vkCmdSetStencilCompareMask;
	extern PFN_vkCmdSetStencilWriteMask pfn_vkCmdSetStencilWriteMask;
	extern PFN_vkCmdSetStencilReference pfn_vkCmdSetStencilReference;
	extern PFN_vkCmdBindDescriptorSets pfn_vkCmdBindDescriptorSets;
	extern PFN_vkCmdBindIndexBuffer pfn_vkCmdBindIndexBuffer;
	extern PFN_vkCmdBindVertexBuffers pfn_vkCmdBindVertexBuffers;
	extern PFN_vkCmdDraw pfn_vkCmdDraw;
	extern PFN_vkCmdDrawIndexed pfn_vkCmdDrawIndexed;
	extern PFN_vkCmdDrawIndirect pfn_vkCmdDrawIndirect;
	extern PFN_vkCmdDrawIndexedIndirect pfn_vkCmdDrawIndexedIndirect;
	extern PFN_vkCmdDispatch pfn_vkCmdDispatch;
	extern PFN_vkCmdDispatchIndirect pfn_vkCmdDispatchIndirect;
	extern PFN_vkCmdCopyBuffer pfn_vkCmdCopyBuffer;
	extern PFN_vkCmdCopyImage pfn_vkCmdCopyImage;
	extern PFN_vkCmdBlitImage pfn_vkCmdBlitImage;
	extern PFN_vkCmdCopyBufferToImage pfn_vkCmdCopyBufferToImage;
	extern PFN_vkCmdCopyImageToBuffer pfn_vkCmdCopyImageToBuffer;
	extern PFN_vkCmdUpdateBuffer pfn_vkCmdUpdateBuffer;
	extern PFN_vkCmdFillBuffer pfn_vkCmdFillBuffer;
	extern PFN_vkCmdClearColorImage pfn_vkCmdClearColorImage;
	extern PFN_vkCmdClearDepthStencilImage pfn_vkCmdClearDepthStencilImage;
	extern PFN_vkCmdClearAttachments pfn_vkCmdClearAttachments;
	extern PFN_vkCmdResolveImage pfn_vkCmdResolveImage;
	extern PFN_vkCmdSetEvent pfn_vkCmdSetEvent;
	extern PFN_vkCmdResetEvent pfn_vkCmdResetEvent;
	extern PFN_vkCmdWaitEvents pfn_vkCmdWaitEvents;
	extern PFN_vkCmdPipelineBarrier pfn_vkCmdPipelineBarrier;
	extern PFN_vkCmdBeginQuery pfn_vkCmdBeginQuery;
	extern PFN_vkCmdEndQuery pfn_vkCmdEndQuery;
	extern PFN_vkCmdResetQueryPool pfn_vkCmdResetQueryPool;
	extern PFN_vkCmdWriteTimestamp pfn_vkCmdWriteTimestamp;
	extern PFN_vkCmdCopyQueryPoolResults pfn_vkCmdCopyQueryPoolResults;
	extern PFN_vkCmdPushConstants pfn_vkCmdPushConstants;
	extern PFN_vkCmdBeginRenderPass pfn_vkCmdBeginRenderPass;
	extern PFN_vkCmdNextSubpass pfn_vkCmdNextSubpass;
	extern PFN_vkCmdEndRenderPass pfn_vkCmdEndRenderPass;
	extern PFN_vkCmdExecuteCommands pfn_vkCmdExecuteCommands;

	// Vulkan 1.1
	extern PFN_vkBindBufferMemory2 pfn_vkBindBufferMemory2;
	extern PFN_vkBindImageMemory2 pfn_vkBindImageMemory2;
	extern PFN_vkGetDeviceGroupPeerMemoryFeatures pfn_vkGetDeviceGroupPeerMemoryFeatures;
	extern PFN_vkCmdSetDeviceMask pfn_vkCmdSetDeviceMask;
	extern PFN_vkCmdDispatchBase pfn_vkCmdDispatchBase;
	extern PFN_vkGetImageMemoryRequirements2 pfn_vkGetImageMemoryRequirements2;
	extern PFN_vkGetBufferMemoryRequirements2 pfn_vkGetBufferMemoryRequirements2;
	extern PFN_vkGetImageSparseMemoryRequirements2 pfn_vkGetImageSparseMemoryRequirements2;
	extern PFN_vkTrimCommandPool pfn_vkTrimCommandPool;
	extern PFN_vkGetDeviceQueue2 pfn_vkGetDeviceQueue2;
	extern PFN_vkCreateSamplerYcbcrConversion pfn_vkCreateSamplerYcbcrConversion;
	extern PFN_vkDestroySamplerYcbcrConversion pfn_vkDestroySamplerYcbcrConversion;
	extern PFN_vkCreateDescriptorUpdateTemplate pfn_vkCreateDescriptorUpdateTemplate;
	extern PFN_vkDestroyDescriptorUpdateTemplate pfn_vkDestroyDescriptorUpdateTemplate;
	extern PFN_vkUpdateDescriptorSetWithTemplate pfn_vkUpdateDescriptorSetWithTemplate;
	extern PFN_vkGetDescriptorSetLayoutSupport pfn_vkGetDescriptorSetLayoutSupport;

	// Vulkan 1.2
	extern PFN_vkCmdDrawIndirectCount pfn_vkCmdDrawIndirectCount;
	extern PFN_vkCmdDrawIndexedIndirectCount pfn_vkCmdDrawIndexedIndirectCount;
	extern PFN_vkCreateRenderPass2 pfn_vkCreateRenderPass2;
	extern PFN_vkCmdBeginRenderPass2 pfn_vkCmdBeginRenderPass2;
	extern PFN_vkCmdNextSubpass2 pfn_vkCmdNextSubpass2;
	extern PFN_vkCmdEndRenderPass2 pfn_vkCmdEndRenderPass2;
	extern PFN_vkResetQueryPool pfn_vkResetQueryPool;
	extern PFN_vkGetSemaphoreCounterValue pfn_vkGetSemaphoreCounterValue;
	extern PFN_vkWaitSemaphores pfn_vkWaitSemaphores;
	extern PFN_vkSignalSemaphore pfn_vkSignalSemaphore;
	extern PFN_vkGetBufferDeviceAddress pfn_vkGetBufferDeviceAddress;
	extern PFN_vkGetBufferOpaqueCaptureAddress pfn_vkGetBufferOpaqueCaptureAddress;
	extern PFN_vkGetDeviceMemoryOpaqueCaptureAddress pfn_vkGetDeviceMemoryOpaqueCaptureAddress;

	// Vulkan 1.3
	extern PFN_vkCreatePrivateDataSlot pfn_vkCreatePrivateDataSlot;
	extern PFN_vkDestroyPrivateDataSlot pfn_vkDestroyPrivateDataSlot;
	extern PFN_vkSetPrivateData pfn_vkSetPrivateData;
	extern PFN_vkGetPrivateData pfn_vkGetPrivateData;
	extern PFN_vkCmdSetEvent2 pfn_vkCmdSetEvent2;
	extern PFN_vkCmdResetEvent2 pfn_vkCmdResetEvent2;
	extern PFN_vkCmdWaitEvents2 pfn_vkCmdWaitEvents2;
	extern PFN_vkCmdPipelineBarrier2 pfn_vkCmdPipelineBarrier2;
	extern PFN_vkCmdWriteTimestamp2 pfn_vkCmdWriteTimestamp2;
	extern PFN_vkQueueSubmit2 pfn_vkQueueSubmit2;
	extern PFN_vkCmdCopyBuffer2 pfn_vkCmdCopyBuffer2;
	extern PFN_vkCmdCopyImage2 pfn_vkCmdCopyImage2;
	extern PFN_vkCmdCopyBufferToImage2 pfn_vkCmdCopyBufferToImage2;
	extern PFN_vkCmdCopyImageToBuffer2 pfn_vkCmdCopyImageToBuffer2;
	extern PFN_vkCmdBlitImage2 pfn_vkCmdBlitImage2;
	extern PFN_vkCmdResolveImage2 pfn_vkCmdResolveImage2;
	extern PFN_vkCmdBeginRendering pfn_vkCmdBeginRendering;
	extern PFN_vkCmdEndRendering pfn_vkCmdEndRendering;
	extern PFN_vkCmdSetCullMode pfn_vkCmdSetCullMode;
	extern PFN_vkCmdSetFrontFace pfn_vkCmdSetFrontFace;
	extern PFN_vkCmdSetPrimitiveTopology pfn_vkCmdSetPrimitiveTopology;
	extern PFN_vkCmdSetViewportWithCount pfn_vkCmdSetViewportWithCount;
	extern PFN_vkCmdSetScissorWithCount pfn_vkCmdSetScissorWithCount;
	extern PFN_vkCmdBindVertexBuffers2 pfn_vkCmdBindVertexBuffers2;
	extern PFN_vkCmdSetDepthTestEnable pfn_vkCmdSetDepthTestEnable;
	extern PFN_vkCmdSetDepthWriteEnable pfn_vkCmdSetDepthWriteEnable;
	extern PFN_vkCmdSetDepthCompareOp pfn_vkCmdSetDepthCompareOp;
	extern PFN_vkCmdSetDepthBoundsTestEnable pfn_vkCmdSetDepthBoundsTestEnable;
	extern PFN_vkCmdSetStencilTestEnable pfn_vkCmdSetStencilTestEnable;
	extern PFN_vkCmdSetStencilOp pfn_vkCmdSetStencilOp;
	extern PFN_vkCmdSetRasterizerDiscardEnable pfn_vkCmdSetRasterizerDiscardEnable;
	extern PFN_vkCmdSetDepthBiasEnable pfn_vkCmdSetDepthBiasEnable;
	extern PFN_vkCmdSetPrimitiveRestartEnable pfn_vkCmdSetPrimitiveRestartEnable;
	extern PFN_vkGetDeviceBufferMemoryRequirements pfn_vkGetDeviceBufferMemoryRequirements;
	extern PFN_vkGetDeviceImageMemoryRequirements pfn_vkGetDeviceImageMemoryRequirements;
	extern PFN_vkGetDeviceImageSparseMemoryRequirements pfn_vkGetDeviceImageSparseMemoryRequirements;

	// Vulkan 1.4
	/* extern PFN_vkCmdSetLineStipple pfn_vkCmdSetLineStipple;
	extern PFN_vkMapMemory2 pfn_vkMapMemory2;
	extern PFN_vkUnmapMemory2 pfn_vkUnmapMemory2;
	extern PFN_vkCmdBindIndexBuffer2 pfn_vkCmdBindIndexBuffer2;
	extern PFN_vkGetRenderingAreaGranularity pfn_vkGetRenderingAreaGranularity;
	extern PFN_vkGetDeviceImageSubresourceLayout pfn_vkGetDeviceImageSubresourceLayout;
	extern PFN_vkGetImageSubresourceLayout2 pfn_vkGetImageSubresourceLayout2;
	extern PFN_vkCmdPushDescriptorSet pfn_vkCmdPushDescriptorSet;
	extern PFN_vkCmdPushDescriptorSetWithTemplate pfn_vkCmdPushDescriptorSetWithTemplate;
	extern PFN_vkCmdSetRenderingAttachmentLocations pfn_vkCmdSetRenderingAttachmentLocations;
	extern PFN_vkCmdSetRenderingInputAttachmentIndices pfn_vkCmdSetRenderingInputAttachmentIndices;
	extern PFN_vkCmdBindDescriptorSets2 pfn_vkCmdBindDescriptorSets2;
	extern PFN_vkCmdPushConstants2 pfn_vkCmdPushConstants2;
	extern PFN_vkCmdPushDescriptorSet2 pfn_vkCmdPushDescriptorSet2;
	extern PFN_vkCmdPushDescriptorSetWithTemplate2 pfn_vkCmdPushDescriptorSetWithTemplate2;
	extern PFN_vkCopyMemoryToImage pfn_vkCopyMemoryToImage;
	extern PFN_vkCopyImageToMemory pfn_vkCopyImageToMemory;
	extern PFN_vkCopyImageToImage pfn_vkCopyImageToImage;
	extern PFN_vkTransitionImageLayout pfn_vkTransitionImageLayout; */

	bool init_vulkan_device();
	void destroy_vulkan_device();

// Vulkan 1.0
#define vkGetDeviceQueue(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDeviceQueue(__VA_ARGS__))
#define vkQueueSubmit(...) CHECK_VK_RESULT(pfn_vkQueueSubmit(__VA_ARGS__))
#define vkQueueWaitIdle(...) CHECK_VK_RESULT(pfn_vkQueueWaitIdle(__VA_ARGS__))
#define vkDeviceWaitIdle(...) CHECK_VK_RESULT(pfn_vkDeviceWaitIdle(__VA_ARGS__))
#define vkAllocateMemory(...) CHECK_VK_RESULT(pfn_vkAllocateMemory(__VA_ARGS__))
#define vkFreeMemory(...) FOCUS_FOR_VK_DEBUG(pfn_vkFreeMemory(__VA_ARGS__))
#define vkMapMemory(...) CHECK_VK_RESULT(pfn_vkMapMemory(__VA_ARGS__))
#define vkUnmapMemory(...) FOCUS_FOR_VK_DEBUG(pfn_vkUnmapMemory(__VA_ARGS__))
#define vkFlushMappedMemoryRanges(...) CHECK_VK_RESULT(pfn_vkFlushMappedMemoryRanges(__VA_ARGS__))
#define vkInvalidateMappedMemoryRanges(...) CHECK_VK_RESULT(pfn_vkInvalidateMappedMemoryRanges(__VA_ARGS__))
#define vkGetDeviceMemoryCommitment(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDeviceMemoryCommitment(__VA_ARGS__))
#define vkBindBufferMemory(...) CHECK_VK_RESULT(pfn_vkBindBufferMemory(__VA_ARGS__))
#define vkBindImageMemory(...) CHECK_VK_RESULT(pfn_vkBindImageMemory(__VA_ARGS__))
#define vkGetBufferMemoryRequirements(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetBufferMemoryRequirements(__VA_ARGS__))
#define vkGetImageMemoryRequirements(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetImageMemoryRequirements(__VA_ARGS__))
#define vkGetImageSparseMemoryRequirements(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetImageSparseMemoryRequirements(__VA_ARGS__))
#define vkQueueBindSparse(...) CHECK_VK_RESULT(pfn_vkQueueBindSparse(__VA_ARGS__))
#define vkCreateFence(...) CHECK_VK_RESULT(pfn_vkCreateFence(__VA_ARGS__))
#define vkDestroyFence(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyFence(__VA_ARGS__))
#define vkResetFences(...) CHECK_VK_RESULT(pfn_vkResetFences(__VA_ARGS__))
#define vkGetFenceStatus(...) CHECK_VK_RESULT(pfn_vkGetFenceStatus(__VA_ARGS__))
#define vkWaitForFences(...) CHECK_VK_RESULT(pfn_vkWaitForFences(__VA_ARGS__))
#define vkCreateSemaphore(...) CHECK_VK_RESULT(pfn_vkCreateSemaphore(__VA_ARGS__))
#define vkDestroySemaphore(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroySemaphore(__VA_ARGS__))
#define vkCreateEvent(...) CHECK_VK_RESULT(pfn_vkCreateEvent(__VA_ARGS__))
#define vkDestroyEvent(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyEvent(__VA_ARGS__))
#define vkGetEventStatus(...) CHECK_VK_RESULT(pfn_vkGetEventStatus(__VA_ARGS__))
#define vkSetEvent(...) CHECK_VK_RESULT(pfn_vkSetEvent(__VA_ARGS__))
#define vkResetEvent(...) CHECK_VK_RESULT(pfn_vkResetEvent(__VA_ARGS__))
#define vkCreateQueryPool(...) CHECK_VK_RESULT(pfn_vkCreateQueryPool(__VA_ARGS__))
#define vkDestroyQueryPool(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyQueryPool(__VA_ARGS__))
#define vkGetQueryPoolResults(...) CHECK_VK_RESULT(pfn_vkGetQueryPoolResults(__VA_ARGS__))
#define vkCreateBuffer(...) CHECK_VK_RESULT(pfn_vkCreateBuffer(__VA_ARGS__))
#define vkDestroyBuffer(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyBuffer(__VA_ARGS__))
#define vkCreateBufferView(...) CHECK_VK_RESULT(pfn_vkCreateBufferView(__VA_ARGS__))
#define vkDestroyBufferView(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyBufferView(__VA_ARGS__))
#define vkCreateImage(...) CHECK_VK_RESULT(pfn_vkCreateImage(__VA_ARGS__))
#define vkDestroyImage(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyImage(__VA_ARGS__))
#define vkGetImageSubresourceLayout(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetImageSubresourceLayout(__VA_ARGS__))
#define vkCreateImageView(...) CHECK_VK_RESULT(pfn_vkCreateImageView(__VA_ARGS__))
#define vkDestroyImageView(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyImageView(__VA_ARGS__))
#define vkCreateShaderModule(...) CHECK_VK_RESULT(pfn_vkCreateShaderModule(__VA_ARGS__))
#define vkDestroyShaderModule(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyShaderModule(__VA_ARGS__))
#define vkCreatePipelineCache(...) CHECK_VK_RESULT(pfn_vkCreatePipelineCache(__VA_ARGS__))
#define vkDestroyPipelineCache(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyPipelineCache(__VA_ARGS__))
#define vkGetPipelineCacheData(...) CHECK_VK_RESULT(pfn_vkGetPipelineCacheData(__VA_ARGS__))
#define vkMergePipelineCaches(...) CHECK_VK_RESULT(pfn_vkMergePipelineCaches(__VA_ARGS__))
#define vkCreateGraphicsPipelines(...) CHECK_VK_RESULT(pfn_vkCreateGraphicsPipelines(__VA_ARGS__))
#define vkCreateComputePipelines(...) CHECK_VK_RESULT(pfn_vkCreateComputePipelines(__VA_ARGS__))
#define vkDestroyPipeline(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyPipeline(__VA_ARGS__))
#define vkCreatePipelineLayout(...) CHECK_VK_RESULT(pfn_vkCreatePipelineLayout(__VA_ARGS__))
#define vkDestroyPipelineLayout(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyPipelineLayout(__VA_ARGS__))
#define vkCreateSampler(...) CHECK_VK_RESULT(pfn_vkCreateSampler(__VA_ARGS__))
#define vkDestroySampler(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroySampler(__VA_ARGS__))
#define vkCreateDescriptorSetLayout(...) CHECK_VK_RESULT(pfn_vkCreateDescriptorSetLayout(__VA_ARGS__))
#define vkDestroyDescriptorSetLayout(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyDescriptorSetLayout(__VA_ARGS__))
#define vkCreateDescriptorPool(...) CHECK_VK_RESULT(pfn_vkCreateDescriptorPool(__VA_ARGS__))
#define vkDestroyDescriptorPool(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyDescriptorPool(__VA_ARGS__))
#define vkResetDescriptorPool(...) CHECK_VK_RESULT(pfn_vkResetDescriptorPool(__VA_ARGS__))
#define vkAllocateDescriptorSets(...) CHECK_VK_RESULT(pfn_vkAllocateDescriptorSets(__VA_ARGS__))
#define vkFreeDescriptorSets(...) CHECK_VK_RESULT(pfn_vkFreeDescriptorSets(__VA_ARGS__))
#define vkUpdateDescriptorSets(...) FOCUS_FOR_VK_DEBUG(pfn_vkUpdateDescriptorSets(__VA_ARGS__))
#define vkCreateFramebuffer(...) CHECK_VK_RESULT(pfn_vkCreateFramebuffer(__VA_ARGS__))
#define vkDestroyFramebuffer(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyFramebuffer(__VA_ARGS__))
#define vkCreateRenderPass(...) CHECK_VK_RESULT(pfn_vkCreateRenderPass(__VA_ARGS__))
#define vkDestroyRenderPass(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyRenderPass(__VA_ARGS__))
#define vkGetRenderAreaGranularity(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetRenderAreaGranularity(__VA_ARGS__))
#define vkCreateCommandPool(...) CHECK_VK_RESULT(pfn_vkCreateCommandPool(__VA_ARGS__))
#define vkDestroyCommandPool(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyCommandPool(__VA_ARGS__))
#define vkResetCommandPool(...) CHECK_VK_RESULT(pfn_vkResetCommandPool(__VA_ARGS__))
#define vkAllocateCommandBuffers(...) CHECK_VK_RESULT(pfn_vkAllocateCommandBuffers(__VA_ARGS__))
#define vkFreeCommandBuffers(...) FOCUS_FOR_VK_DEBUG(pfn_vkFreeCommandBuffers(__VA_ARGS__))
#define vkBeginCommandBuffer(...) CHECK_VK_RESULT(pfn_vkBeginCommandBuffer(__VA_ARGS__))
#define vkEndCommandBuffer(...) CHECK_VK_RESULT(pfn_vkEndCommandBuffer(__VA_ARGS__))
#define vkResetCommandBuffer(...) CHECK_VK_RESULT(pfn_vkResetCommandBuffer(__VA_ARGS__))
#define vkCmdBindPipeline(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBindPipeline(__VA_ARGS__))
#define vkCmdSetViewport(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetViewport(__VA_ARGS__))
#define vkCmdSetScissor(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetScissor(__VA_ARGS__))
#define vkCmdSetLineWidth(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetLineWidth(__VA_ARGS__))
#define vkCmdSetDepthBias(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetDepthBias(__VA_ARGS__))
#define vkCmdSetBlendConstants(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetBlendConstants(__VA_ARGS__))
#define vkCmdSetDepthBounds(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetDepthBounds(__VA_ARGS__))
#define vkCmdSetStencilCompareMask(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetStencilCompareMask(__VA_ARGS__))
#define vkCmdSetStencilWriteMask(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetStencilWriteMask(__VA_ARGS__))
#define vkCmdSetStencilReference(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetStencilReference(__VA_ARGS__))
#define vkCmdBindDescriptorSets(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBindDescriptorSets(__VA_ARGS__))
#define vkCmdBindIndexBuffer(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBindIndexBuffer(__VA_ARGS__))
#define vkCmdBindVertexBuffers(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBindVertexBuffers(__VA_ARGS__))
#define vkCmdDraw(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDraw(__VA_ARGS__))
#define vkCmdDrawIndexed(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDrawIndexed(__VA_ARGS__))
#define vkCmdDrawIndirect(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDrawIndirect(__VA_ARGS__))
#define vkCmdDrawIndexedIndirect(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDrawIndexedIndirect(__VA_ARGS__))
#define vkCmdDispatch(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDispatch(__VA_ARGS__))
#define vkCmdDispatchIndirect(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDispatchIndirect(__VA_ARGS__))
#define vkCmdCopyBuffer(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyBuffer(__VA_ARGS__))
#define vkCmdCopyImage(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyImage(__VA_ARGS__))
#define vkCmdBlitImage(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBlitImage(__VA_ARGS__))
#define vkCmdCopyBufferToImage(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyBufferToImage(__VA_ARGS__))
#define vkCmdCopyImageToBuffer(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyImageToBuffer(__VA_ARGS__))
#define vkCmdUpdateBuffer(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdUpdateBuffer(__VA_ARGS__))
#define vkCmdFillBuffer(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdFillBuffer(__VA_ARGS__))
#define vkCmdClearColorImage(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdClearColorImage(__VA_ARGS__))
#define vkCmdClearDepthStencilImage(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdClearDepthStencilImage(__VA_ARGS__))
#define vkCmdClearAttachments(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdClearAttachments(__VA_ARGS__))
#define vkCmdResolveImage(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdResolveImage(__VA_ARGS__))
#define vkCmdSetEvent(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetEvent(__VA_ARGS__))
#define vkCmdResetEvent(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdResetEvent(__VA_ARGS__))
#define vkCmdWaitEvents(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdWaitEvents(__VA_ARGS__))
#define vkCmdPipelineBarrier(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdPipelineBarrier(__VA_ARGS__))
#define vkCmdBeginQuery(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBeginQuery(__VA_ARGS__))
#define vkCmdEndQuery(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdEndQuery(__VA_ARGS__))
#define vkCmdResetQueryPool(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdResetQueryPool(__VA_ARGS__))
#define vkCmdWriteTimestamp(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdWriteTimestamp(__VA_ARGS__))
#define vkCmdCopyQueryPoolResults(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyQueryPoolResults(__VA_ARGS__))
#define vkCmdPushConstants(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdPushConstants(__VA_ARGS__))
#define vkCmdBeginRenderPass(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBeginRenderPass(__VA_ARGS__))
#define vkCmdNextSubpass(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdNextSubpass(__VA_ARGS__))
#define vkCmdEndRenderPass(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdEndRenderPass(__VA_ARGS__))
#define vkCmdExecuteCommands(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdExecuteCommands(__VA_ARGS__))

// Vulkan 1.1
#define vkBindBufferMemory2(...) CHECK_VK_RESULT(pfn_vkBindBufferMemory2(__VA_ARGS__))
#define vkBindImageMemory2(...) CHECK_VK_RESULT(pfn_vkBindImageMemory2(__VA_ARGS__))
#define vkGetDeviceGroupPeerMemoryFeatures(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDeviceGroupPeerMemoryFeatures(__VA_ARGS__))
#define vkCmdSetDeviceMask(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetDeviceMask(__VA_ARGS__))
#define vkCmdDispatchBase(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDispatchBase(__VA_ARGS__))
#define vkGetImageMemoryRequirements2(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetImageMemoryRequirements2(__VA_ARGS__))
#define vkGetBufferMemoryRequirements2(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetBufferMemoryRequirements2(__VA_ARGS__))
#define vkGetImageSparseMemoryRequirements2(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetImageSparseMemoryRequirements2(__VA_ARGS__))
#define vkTrimCommandPool(...) FOCUS_FOR_VK_DEBUG(pfn_vkTrimCommandPool(__VA_ARGS__))
#define vkGetDeviceQueue2(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDeviceQueue2(__VA_ARGS__))
#define vkCreateSamplerYcbcrConversion(...) CHECK_VK_RESULT(pfn_vkCreateSamplerYcbcrConversion(__VA_ARGS__))
#define vkDestroySamplerYcbcrConversion(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroySamplerYcbcrConversion(__VA_ARGS__))
#define vkCreateDescriptorUpdateTemplate(...) CHECK_VK_RESULT(pfn_vkCreateDescriptorUpdateTemplate(__VA_ARGS__))
#define vkDestroyDescriptorUpdateTemplate(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyDescriptorUpdateTemplate(__VA_ARGS__))
#define vkUpdateDescriptorSetWithTemplate(...) FOCUS_FOR_VK_DEBUG(pfn_vkUpdateDescriptorSetWithTemplate(__VA_ARGS__))
#define vkGetDescriptorSetLayoutSupport(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDescriptorSetLayoutSupport(__VA_ARGS__))

// Vulkan 1.2
#define vkCmdDrawIndirectCount(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDrawIndirectCount(__VA_ARGS__))
#define vkCmdDrawIndexedIndirectCount(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdDrawIndexedIndirectCount(__VA_ARGS__))
#define vkCreateRenderPass2(...) CHECK_VK_RESULT(pfn_vkCreateRenderPass2(__VA_ARGS__))
#define vkCmdBeginRenderPass2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBeginRenderPass2(__VA_ARGS__))
#define vkCmdNextSubpass2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdNextSubpass2(__VA_ARGS__))
#define vkCmdEndRenderPass2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdEndRenderPass2(__VA_ARGS__))
#define vkResetQueryPool(...) FOCUS_FOR_VK_DEBUG(pfn_vkResetQueryPool(__VA_ARGS__))
#define vkGetSemaphoreCounterValue(...) CHECK_VK_RESULT(pfn_vkGetSemaphoreCounterValue(__VA_ARGS__))
#define vkWaitSemaphores(...) CHECK_VK_RESULT(pfn_vkWaitSemaphores(__VA_ARGS__))
#define vkSignalSemaphore(...) CHECK_VK_RESULT(pfn_vkSignalSemaphore(__VA_ARGS__))
#define vkGetBufferDeviceAddress(...) FOCUS_FOR_VK_DEBUG_AND_RETURN(pfn_vkGetBufferDeviceAddress(__VA_ARGS__), VkDeviceAddress)
#define vkGetBufferOpaqueCaptureAddress(...) FOCUS_FOR_VK_DEBUG_AND_RETURN(pfn_vkGetBufferOpaqueCaptureAddress(__VA_ARGS__), uint64_t)
#define vkGetDeviceMemoryOpaqueCaptureAddress(...) FOCUS_FOR_VK_DEBUG_AND_RETURN(pfn_vkGetDeviceMemoryOpaqueCaptureAddress(__VA_ARGS__), uint64_t)

// Vulkan 1.3
#define vkCreatePrivateDataSlot(...) CHECK_VK_RESULT(pfn_vkCreatePrivateDataSlot(__VA_ARGS__))
#define vkDestroyPrivateDataSlot(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroyPrivateDataSlot(__VA_ARGS__))
#define vkSetPrivateData(...) CHECK_VK_RESULT(pfn_vkSetPrivateData(__VA_ARGS__))
#define vkGetPrivateData(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetPrivateData(__VA_ARGS__))
#define vkCmdSetEvent2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetEvent2(__VA_ARGS__))
#define vkCmdResetEvent2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdResetEvent2(__VA_ARGS__))
#define vkCmdWaitEvents2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdWaitEvents2(__VA_ARGS__))
#define vkCmdPipelineBarrier2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdPipelineBarrier2(__VA_ARGS__))
#define vkCmdWriteTimestamp2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdWriteTimestamp2(__VA_ARGS__))
#define vkQueueSubmit2(...) CHECK_VK_RESULT(pfn_vkQueueSubmit2(__VA_ARGS__))
#define vkCmdCopyBuffer2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyBuffer2(__VA_ARGS__))
#define vkCmdCopyImage2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyImage2(__VA_ARGS__))
#define vkCmdCopyBufferToImage2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyBufferToImage2(__VA_ARGS__))
#define vkCmdCopyImageToBuffer2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdCopyImageToBuffer2(__VA_ARGS__))
#define vkCmdBlitImage2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBlitImage2(__VA_ARGS__))
#define vkCmdResolveImage2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdResolveImage2(__VA_ARGS__))
#define vkCmdBeginRendering(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBeginRendering(__VA_ARGS__))
#define vkCmdEndRendering(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdEndRendering(__VA_ARGS__))
#define vkCmdSetCullMode(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetCullMode(__VA_ARGS__))
#define vkCmdSetFrontFace(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetFrontFace(__VA_ARGS__))
#define vkCmdSetPrimitiveTopology(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetPrimitiveTopology(__VA_ARGS__))
#define vkCmdSetViewportWithCount(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetViewportWithCount(__VA_ARGS__))
#define vkCmdSetScissorWithCount(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetScissorWithCount(__VA_ARGS__))
#define vkCmdBindVertexBuffers2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBindVertexBuffers2(__VA_ARGS__))
#define vkCmdSetDepthTestEnable(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetDepthTestEnable(__VA_ARGS__))
#define vkCmdSetDepthWriteEnable(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetDepthWriteEnable(__VA_ARGS__))
#define vkCmdSetDepthCompareOp(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetDepthCompareOp(__VA_ARGS__))
#define vkCmdSetDepthBoundsTestEnable(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetDepthBoundsTestEnable(__VA_ARGS__))
#define vkCmdSetStencilTestEnable(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetStencilTestEnable(__VA_ARGS__))
#define vkCmdSetStencilOp(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetStencilOp(__VA_ARGS__))
#define vkCmdSetRasterizerDiscardEnable(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetRasterizerDiscardEnable(__VA_ARGS__))
#define vkCmdSetDepthBiasEnable(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetDepthBiasEnable(__VA_ARGS__))
#define vkCmdSetPrimitiveRestartEnable(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetPrimitiveRestartEnable(__VA_ARGS__))
#define vkGetDeviceBufferMemoryRequirements(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDeviceBufferMemoryRequirements(__VA_ARGS__))
#define vkGetDeviceImageMemoryRequirements(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDeviceImageMemoryRequirements(__VA_ARGS__))
#define vkGetDeviceImageSparseMemoryRequirements(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDeviceImageSparseMemoryRequirements(__VA_ARGS__))

// Vulkan 1.4
/* #define vkCmdSetLineStipple(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetLineStipple(__VA_ARGS__))
#define vkMapMemory2(...) CHECK_VK_RESULT(pfn_vkMapMemory2(__VA_ARGS__))
#define vkUnmapMemory2(...) CHECK_VK_RESULT(pfn_vkUnmapMemory2(__VA_ARGS__))
#define vkCmdBindIndexBuffer2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBindIndexBuffer2(__VA_ARGS__))
#define vkGetRenderingAreaGranularity(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetRenderingAreaGranularity(__VA_ARGS__))
#define vkGetDeviceImageSubresourceLayout(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetDeviceImageSubresourceLayout(__VA_ARGS__))
#define vkGetImageSubresourceLayout2(...) FOCUS_FOR_VK_DEBUG(pfn_vkGetImageSubresourceLayout2(__VA_ARGS__))
#define vkCmdPushDescriptorSet(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdPushDescriptorSet(__VA_ARGS__))
#define vkCmdPushDescriptorSetWithTemplate(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdPushDescriptorSetWithTemplate(__VA_ARGS__))
#define vkCmdSetRenderingAttachmentLocations(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetRenderingAttachmentLocations(__VA_ARGS__))
#define vkCmdSetRenderingInputAttachmentIndices(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdSetRenderingInputAttachmentIndices(__VA_ARGS__))
#define vkCmdBindDescriptorSets2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBindDescriptorSets2(__VA_ARGS__))
#define vkCmdPushConstants2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdPushConstants2(__VA_ARGS__))
#define vkCmdPushDescriptorSet2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdPushDescriptorSet2(__VA_ARGS__))
#define vkCmdPushDescriptorSetWithTemplate2(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdPushDescriptorSetWithTemplate2(__VA_ARGS__))
#define vkCopyMemoryToImage(...) CHECK_VK_RESULT(pfn_vkCopyMemoryToImage(__VA_ARGS__))
#define vkCopyImageToMemory(...) CHECK_VK_RESULT(pfn_vkCopyImageToMemory(__VA_ARGS__))
#define vkCopyImageToImage(...) CHECK_VK_RESULT(pfn_vkCopyImageToImage(__VA_ARGS__))
#define vkTransitionImageLayout(...) CHECK_VK_RESULT(pfn_vkTransitionImageLayout(__VA_ARGS__)) */

// Debug extension
#define vkQueueBeginDebugUtilsLabelEXT(...) FOCUS_FOR_VK_DEBUG(pfn_vkQueueBeginDebugUtilsLabelEXT(__VA_ARGS__))
#define vkQueueEndDebugUtilsLabelEXT(...) FOCUS_FOR_VK_DEBUG(pfn_vkQueueEndDebugUtilsLabelEXT(__VA_ARGS__))
#define vkQueueInsertDebugUtilsLabelEXT(...) FOCUS_FOR_VK_DEBUG(pfn_vkQueueInsertDebugUtilsLabelEXT(__VA_ARGS__))
#define vkCmdBeginDebugUtilsLabelEXT(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdBeginDebugUtilsLabelEXT(__VA_ARGS__))
#define vkCmdEndDebugUtilsLabelEXT(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdEndDebugUtilsLabelEXT(__VA_ARGS__))
#define vkCmdInsertDebugUtilsLabelEXT(...) FOCUS_FOR_VK_DEBUG(pfn_vkCmdInsertDebugUtilsLabelEXT(__VA_ARGS__))
// Swapchain extension
#define vkCreateSwapchainKHR(...) CHECK_VK_RESULT(pfn_vkCreateSwapchainKHR(__VA_ARGS__))
#define vkDestroySwapchainKHR(...) FOCUS_FOR_VK_DEBUG(pfn_vkDestroySwapchainKHR(__VA_ARGS__))
#define vkGetSwapchainImagesKHR(...) CHECK_VK_RESULT(pfn_vkGetSwapchainImagesKHR(__VA_ARGS__))
#define vkAcquireNextImageKHR(...) FOCUS_FOR_VK_DEBUG_AND_RETURN(pfn_vkAcquireNextImageKHR(__VA_ARGS__), VkResult)
#define vkQueuePresentKHR(...) FOCUS_FOR_VK_DEBUG_AND_RETURN(pfn_vkQueuePresentKHR(__VA_ARGS__), VkResult)
#define vkGetDeviceGroupPresentCapabilitiesKHR(...) CHECK_VK_RESULT(pfn_vkGetDeviceGroupPresentCapabilitiesKHR(__VA_ARGS__))
#define vkGetDeviceGroupSurfacePresentModesKHR(...) CHECK_VK_RESULT(pfn_vkGetDeviceGroupSurfacePresentModesKHR(__VA_ARGS__))
#define vkAcquireNextImage2KHR(...) FOCUS_FOR_VK_DEBUG_AND_RETURN(pfn_vkAcquireNextImage2KHR(__VA_ARGS__), VkResult)

#define WAIT_FOR_IDLE_VULKAN_DEVICE() vkDeviceWaitIdle(vk_hDevice)

}

#endif /* __RE_VULKAN_DEVICE_H__ */
