#ifndef __RE_VULKAN_H__
#define __RE_VULKAN_H__

#include "RE_Internal Header.hpp"
#ifdef RE_OS_WINDOWS
# define VK_USE_PLATFORM_WIN32_KHR
#elif defined RE_OS_LINUX
# define VK_USE_PLATFORM_WAYLAND_KHR
# define VK_USE_PLATFORM_XLIB_KHR
#endif
#define VK_NO_PROTOTYPES
#include <vulkan/vulkan.h>

namespace RE {
	
	extern VkInstance vk_hInstance;
	
	// Vulkan 1.0
	extern PFN_vkCreateInstance pfn_vkCreateInstance;
	extern PFN_vkDestroyInstance pfn_vkDestroyInstance;
	extern PFN_vkEnumeratePhysicalDevices pfn_vkEnumeratePhysicalDevices;
	extern PFN_vkGetPhysicalDeviceFeatures pfn_vkGetPhysicalDeviceFeatures;
	extern PFN_vkGetPhysicalDeviceFormatProperties pfn_vkGetPhysicalDeviceFormatProperties;
	extern PFN_vkGetPhysicalDeviceImageFormatProperties pfn_vkGetPhysicalDeviceImageFormatProperties;
	extern PFN_vkGetPhysicalDeviceProperties pfn_vkGetPhysicalDeviceProperties;
	extern PFN_vkGetPhysicalDeviceQueueFamilyProperties pfn_vkGetPhysicalDeviceQueueFamilyProperties;
	extern PFN_vkGetPhysicalDeviceMemoryProperties pfn_vkGetPhysicalDeviceMemoryProperties;
	extern PFN_vkGetInstanceProcAddr pfn_vkGetInstanceProcAddr;
	extern PFN_vkGetDeviceProcAddr pfn_vkGetDeviceProcAddr;
	extern PFN_vkCreateDevice pfn_vkCreateDevice;
	extern PFN_vkDestroyDevice pfn_vkDestroyDevice;
	extern PFN_vkEnumerateInstanceExtensionProperties pfn_vkEnumerateInstanceExtensionProperties;
	extern PFN_vkEnumerateDeviceExtensionProperties pfn_vkEnumerateDeviceExtensionProperties;
	extern PFN_vkEnumerateInstanceLayerProperties pfn_vkEnumerateInstanceLayerProperties;
	extern PFN_vkEnumerateDeviceLayerProperties pfn_vkEnumerateDeviceLayerProperties;
	extern PFN_vkGetDeviceQueue pfn_vkGetDeviceQueue;
	extern PFN_vkQueueSubmit pfn_vkQueueSubmit;
	extern PFN_vkQueueWaitIdle pfn_vkQueueWaitIdle;
	extern PFN_vkDeviceWaitIdle pfn_vkDeviceWaitIdle;
	extern PFN_vkAllocateMemory pfn_vkAllocateMemory;
	extern PFN_vkFreeMemory pfn_vkFreeMemory;
	extern PFN_vkMapMemory pfn_vkMapMemory;
	extern PFN_vkUnmapMemory pfn_vkUnmapMemory;
	extern PFN_vkFlushMappedMemoryRanges pfn_vkFlushMappedMemoryRanges;
	extern PFN_vkInvalidateMappedMemoryRanges pfn_vkInvalidateMappedMemoryRanges;
	extern PFN_vkGetDeviceMemoryCommitment pfn_vkGetDeviceMemoryCommitment;
	extern PFN_vkBindBufferMemory pfn_vkBindBufferMemory;
	extern PFN_vkBindImageMemory pfn_vkBindImageMemory;
	extern PFN_vkGetBufferMemoryRequirements pfn_vkGetBufferMemoryRequirements;
	extern PFN_vkGetImageMemoryRequirements pfn_vkGetImageMemoryRequirements;
	extern PFN_vkGetImageSparseMemoryRequirements pfn_vkGetImageSparseMemoryRequirements;
	extern PFN_vkGetPhysicalDeviceSparseImageFormatProperties pfn_vkGetPhysicalDeviceSparseImageFormatProperties;
	extern PFN_vkQueueBindSparse pfn_vkQueueBindSparse;
	extern PFN_vkCreateFence pfn_vkCreateFence;
	extern PFN_vkDestroyFence pfn_vkDestroyFence;
	extern PFN_vkResetFences pfn_vkResetFences;
	extern PFN_vkGetFenceStatus pfn_vkGetFenceStatus;
	extern PFN_vkWaitForFences pfn_vkWaitForFences;
	extern PFN_vkCreateSemaphore pfn_vkCreateSemaphore;
	extern PFN_vkDestroySemaphore pfn_vkDestroySemaphore;
	extern PFN_vkCreateEvent pfn_vkCreateEvent;
	extern PFN_vkDestroyEvent pfn_vkDestroyEvent;
	extern PFN_vkGetEventStatus pfn_vkGetEventStatus;
	extern PFN_vkSetEvent pfn_vkSetEvent;
	extern PFN_vkResetEvent pfn_vkResetEvent;
	extern PFN_vkCreateQueryPool pfn_vkCreateQueryPool;
	extern PFN_vkDestroyQueryPool pfn_vkDestroyQueryPool;
	extern PFN_vkGetQueryPoolResults pfn_vkGetQueryPoolResults;
	extern PFN_vkCreateBuffer pfn_vkCreateBuffer;
	extern PFN_vkDestroyBuffer pfn_vkDestroyBuffer;
	extern PFN_vkCreateBufferView pfn_vkCreateBufferView;
	extern PFN_vkDestroyBufferView pfn_vkDestroyBufferView;	
	extern PFN_vkCreateImage pfn_vkCreateImage;
	extern PFN_vkDestroyImage pfn_vkDestroyImage;
	extern PFN_vkGetImageSubresourceLayout pfn_vkGetImageSubresourceLayout;
	extern PFN_vkCreateImageView pfn_vkCreateImageView;
	extern PFN_vkDestroyImageView pfn_vkDestroyImageView;
	extern PFN_vkCreateShaderModule pfn_vkCreateShaderModule;
	extern PFN_vkDestroyShaderModule pfn_vkDestroyShaderModule;
	extern PFN_vkCreatePipelineCache pfn_vkCreatePipelineCache;
	extern PFN_vkDestroyPipelineCache pfn_vkDestroyPipelineCache;
	extern PFN_vkGetPipelineCacheData pfn_vkGetPipelineCacheData;
	extern PFN_vkMergePipelineCaches pfn_vkMergePipelineCaches;
	extern PFN_vkCreateGraphicsPipelines pfn_vkCreateGraphicsPipelines;
	extern PFN_vkCreateComputePipelines pfn_vkCreateComputePipelines;
	extern PFN_vkDestroyPipeline pfn_vkDestroyPipeline;
	extern PFN_vkCreatePipelineLayout pfn_vkCreatePipelineLayout;
	extern PFN_vkDestroyPipelineLayout pfn_vkDestroyPipelineLayout;
	extern PFN_vkCreateSampler pfn_vkCreateSampler;
	extern PFN_vkDestroySampler pfn_vkDestroySampler;
	extern PFN_vkCreateDescriptorSetLayout pfn_vkCreateDescriptorSetLayout;
	extern PFN_vkDestroyDescriptorSetLayout pfn_vkDestroyDescriptorSetLayout;
	extern PFN_vkCreateDescriptorPool pfn_vkCreateDescriptorPool;
	extern PFN_vkDestroyDescriptorPool pfn_vkDestroyDescriptorPool;
	extern PFN_vkResetDescriptorPool pfn_vkResetDescriptorPool;
	extern PFN_vkAllocateDescriptorSets pfn_vkAllocateDescriptorSets;
	extern PFN_vkFreeDescriptorSets pfn_vkFreeDescriptorSets;
	extern PFN_vkUpdateDescriptorSets pfn_vkUpdateDescriptorSets;
	extern PFN_vkCreateFramebuffer pfn_vkCreateFramebuffer;
	extern PFN_vkDestroyFramebuffer pfn_vkDestroyFramebuffer;
	extern PFN_vkCreateRenderPass pfn_vkCreateRenderPass;
	extern PFN_vkDestroyRenderPass pfn_vkDestroyRenderPass;
	extern PFN_vkGetRenderAreaGranularity pfn_vkGetRenderAreaGranularity;
	extern PFN_vkCreateCommandPool pfn_vkCreateCommandPool;
	extern PFN_vkDestroyCommandPool pfn_vkDestroyCommandPool;
	extern PFN_vkResetCommandPool pfn_vkResetCommandPool;
	extern PFN_vkAllocateCommandBuffers pfn_vkAllocateCommandBuffers;
	extern PFN_vkFreeCommandBuffers pfn_vkFreeCommandBuffers;
	extern PFN_vkBeginCommandBuffer pfn_vkBeginCommandBuffer;
	extern PFN_vkEndCommandBuffer pfn_vkEndCommandBuffer;
	extern PFN_vkResetCommandBuffer pfn_vkResetCommandBuffer;
	extern PFN_vkCmdBindPipeline pfn_vkCmdBindPipeline;
	extern PFN_vkCmdSetViewport pfn_vkCmdSetViewport;
	extern PFN_vkCmdSetScissor pfn_vkCmdSetScissor;
	extern PFN_vkCmdSetLineWidth pfn_vkCmdSetLineWidth;
	extern PFN_vkCmdSetDepthBias pfn_vkCmdSetDepthBias;
	extern PFN_vkCmdSetBlendConstants pfn_vkCmdSetBlendConstants;
	extern PFN_vkCmdSetDepthBounds pfn_vkCmdSetDepthBounds;
	extern PFN_vkCmdSetStencilCompareMask pfn_vkCmdSetStencilCompareMask;
	extern PFN_vkCmdSetStencilWriteMask pfn_vkCmdSetStencilWriteMask;
	extern PFN_vkCmdSetStencilReference pfn_vkCmdSetStencilReference;
	extern PFN_vkCmdBindDescriptorSets pfn_vkCmdBindDescriptorSets;
	extern PFN_vkCmdBindIndexBuffer pfn_vkCmdBindIndexBuffer;
	extern PFN_vkCmdBindVertexBuffers pfn_vkCmdBindVertexBuffers;
	extern PFN_vkCmdDraw pfn_vkCmdDraw;
	extern PFN_vkCmdDrawIndexed pfn_vkCmdDrawIndexed;
	extern PFN_vkCmdDrawIndirect pfn_vkCmdDrawIndirect;
	extern PFN_vkCmdDrawIndexedIndirect pfn_vkCmdDrawIndexedIndirect;
	extern PFN_vkCmdDispatch pfn_vkCmdDispatch;
	extern PFN_vkCmdDispatchIndirect pfn_vkCmdDispatchIndirect;
	extern PFN_vkCmdCopyBuffer pfn_vkCmdCopyBuffer;
	extern PFN_vkCmdCopyImage pfn_vkCmdCopyImage;
	extern PFN_vkCmdBlitImage pfn_vkCmdBlitImage;
	extern PFN_vkCmdCopyBufferToImage pfn_vkCmdCopyBufferToImage;
	extern PFN_vkCmdCopyImageToBuffer pfn_vkCmdCopyImageToBuffer;
	extern PFN_vkCmdUpdateBuffer pfn_vkCmdUpdateBuffer;
	extern PFN_vkCmdFillBuffer pfn_vkCmdFillBuffer;
	extern PFN_vkCmdClearColorImage pfn_vkCmdClearColorImage;
	extern PFN_vkCmdClearDepthStencilImage pfn_vkCmdClearDepthStencilImage;
	extern PFN_vkCmdClearAttachments pfn_vkCmdClearAttachments;
	extern PFN_vkCmdResolveImage pfn_vkCmdResolveImage;
	extern PFN_vkCmdSetEvent pfn_vkCmdSetEvent;
	extern PFN_vkCmdResetEvent pfn_vkCmdResetEvent;
	extern PFN_vkCmdWaitEvents pfn_vkCmdWaitEvents;
	extern PFN_vkCmdPipelineBarrier pfn_vkCmdPipelineBarrier;
	extern PFN_vkCmdBeginQuery pfn_vkCmdBeginQuery;
	extern PFN_vkCmdEndQuery pfn_vkCmdEndQuery;
	extern PFN_vkCmdResetQueryPool pfn_vkCmdResetQueryPool;
	extern PFN_vkCmdWriteTimestamp pfn_vkCmdWriteTimestamp;
	extern PFN_vkCmdCopyQueryPoolResults pfn_vkCmdCopyQueryPoolResults;
	extern PFN_vkCmdPushConstants pfn_vkCmdPushConstants;
	extern PFN_vkCmdBeginRenderPass pfn_vkCmdBeginRenderPass;
	extern PFN_vkCmdNextSubpass pfn_vkCmdNextSubpass;
	extern PFN_vkCmdEndRenderPass pfn_vkCmdEndRenderPass;
	extern PFN_vkCmdExecuteCommands pfn_vkCmdExecuteCommands;

	// Vulkan 1.1
	extern PFN_vkEnumerateInstanceVersion pfn_vkEnumerateInstanceVersion;
	extern PFN_vkBindBufferMemory2 pfn_vkBindBufferMemory2;
	extern PFN_vkBindImageMemory2 pfn_vkBindImageMemory2;
	extern PFN_vkGetDeviceGroupPeerMemoryFeatures pfn_vkGetDeviceGroupPeerMemoryFeatures;
	extern PFN_vkCmdSetDeviceMask pfn_vkCmdSetDeviceMask;
	extern PFN_vkCmdDispatchBase pfn_vkCmdDispatchBase;
	extern PFN_vkEnumeratePhysicalDeviceGroups pfn_vkEnumeratePhysicalDeviceGroups;
	extern PFN_vkGetImageMemoryRequirements2 pfn_vkGetImageMemoryRequirements2;
	extern PFN_vkGetBufferMemoryRequirements2 pfn_vkGetBufferMemoryRequirements2;
	extern PFN_vkGetImageSparseMemoryRequirements2 pfn_vkGetImageSparseMemoryRequirements2;
	extern PFN_vkGetPhysicalDeviceFeatures2 pfn_vkGetPhysicalDeviceFeatures2;
	extern PFN_vkGetPhysicalDeviceProperties2 pfn_vkGetPhysicalDeviceProperties2;
	extern PFN_vkGetPhysicalDeviceFormatProperties2 pfn_vkGetPhysicalDeviceFormatProperties2;
	extern PFN_vkGetPhysicalDeviceImageFormatProperties2 pfn_vkGetPhysicalDeviceImageFormatProperties2;
	extern PFN_vkGetPhysicalDeviceQueueFamilyProperties2 pfn_vkGetPhysicalDeviceQueueFamilyProperties2;
	extern PFN_vkGetPhysicalDeviceMemoryProperties2 pfn_vkGetPhysicalDeviceMemoryProperties2;
	extern PFN_vkGetPhysicalDeviceSparseImageFormatProperties2 pfn_vkGetPhysicalDeviceSparseImageFormatProperties2;
	extern PFN_vkTrimCommandPool pfn_vkTrimCommandPool;
	extern PFN_vkGetDeviceQueue2 pfn_vkGetDeviceQueue2;
	extern PFN_vkCreateSamplerYcbcrConversion pfn_vkCreateSamplerYcbcrConversion;
	extern PFN_vkDestroySamplerYcbcrConversion pfn_vkDestroySamplerYcbcrConversion;
	extern PFN_vkCreateDescriptorUpdateTemplate pfn_vkCreateDescriptorUpdateTemplate;
	extern PFN_vkDestroyDescriptorUpdateTemplate pfn_vkDestroyDescriptorUpdateTemplate;
	extern PFN_vkUpdateDescriptorSetWithTemplate pfn_vkUpdateDescriptorSetWithTemplate;
	extern PFN_vkGetPhysicalDeviceExternalBufferProperties pfn_vkGetPhysicalDeviceExternalBufferProperties;
	extern PFN_vkGetPhysicalDeviceExternalFenceProperties pfn_vkGetPhysicalDeviceExternalFenceProperties;
	extern PFN_vkGetPhysicalDeviceExternalSemaphoreProperties pfn_vkGetPhysicalDeviceExternalSemaphoreProperties;
	extern PFN_vkGetDescriptorSetLayoutSupport pfn_vkGetDescriptorSetLayoutSupport;

	// Vulkan 1.2
	extern PFN_vkCmdDrawIndirectCount pfn_vkCmdDrawIndirectCount;
	extern PFN_vkCmdDrawIndexedIndirectCount pfn_vkCmdDrawIndexedIndirectCount;
	extern PFN_vkCreateRenderPass2 pfn_vkCreateRenderPass2;
	extern PFN_vkCmdBeginRenderPass2 pfn_vkCmdBeginRenderPass2;
	extern PFN_vkCmdNextSubpass2 pfn_vkCmdNextSubpass2;
	extern PFN_vkCmdEndRenderPass2 pfn_vkCmdEndRenderPass2;
	extern PFN_vkResetQueryPool pfn_vkResetQueryPool;
	extern PFN_vkGetSemaphoreCounterValue pfn_vkGetSemaphoreCounterValue;
	extern PFN_vkWaitSemaphores pfn_vkWaitSemaphores;
	extern PFN_vkSignalSemaphore pfn_vkSignalSemaphore;
	extern PFN_vkGetBufferDeviceAddress pfn_vkGetBufferDeviceAddress;
	extern PFN_vkGetBufferOpaqueCaptureAddress pfn_vkGetBufferOpaqueCaptureAddress;
	extern PFN_vkGetDeviceMemoryOpaqueCaptureAddress pfn_vkGetDeviceMemoryOpaqueCaptureAddress;

	// Vulkan 1.3
	extern PFN_vkGetPhysicalDeviceToolProperties pfn_vkGetPhysicalDeviceToolProperties;
	extern PFN_vkCreatePrivateDataSlot pfn_vkCreatePrivateDataSlot;
	extern PFN_vkDestroyPrivateDataSlot pfn_vkDestroyPrivateDataSlot;
	extern PFN_vkSetPrivateData pfn_vkSetPrivateData;
	extern PFN_vkGetPrivateData pfn_vkGetPrivateData;
	extern PFN_vkCmdSetEvent2 pfn_vkCmdSetEvent2;
	extern PFN_vkCmdResetEvent2 pfn_vkCmdResetEvent2;
	extern PFN_vkCmdWaitEvents2 pfn_vkCmdWaitEvents2;
	extern PFN_vkCmdPipelineBarrier2 pfn_vkCmdPipelineBarrier2;
	extern PFN_vkCmdWriteTimestamp2 pfn_vkCmdWriteTimestamp2;
	extern PFN_vkQueueSubmit2 pfn_vkQueueSubmit2;
	extern PFN_vkCmdCopyBuffer2 pfn_vkCmdCopyBuffer2;
	extern PFN_vkCmdCopyImage2 pfn_vkCmdCopyImage2;
	extern PFN_vkCmdCopyBufferToImage2 pfn_vkCmdCopyBufferToImage2;
	extern PFN_vkCmdCopyImageToBuffer2 pfn_vkCmdCopyImageToBuffer2;
	extern PFN_vkCmdBlitImage2 pfn_vkCmdBlitImage2;
	extern PFN_vkCmdResolveImage2 pfn_vkCmdResolveImage2;
	extern PFN_vkCmdBeginRendering pfn_vkCmdBeginRendering;
	extern PFN_vkCmdEndRendering pfn_vkCmdEndRendering;
	extern PFN_vkCmdSetCullMode pfn_vkCmdSetCullMode;
	extern PFN_vkCmdSetFrontFace pfn_vkCmdSetFrontFace;
	extern PFN_vkCmdSetPrimitiveTopology pfn_vkCmdSetPrimitiveTopology;
	extern PFN_vkCmdSetViewportWithCount pfn_vkCmdSetViewportWithCount;
	extern PFN_vkCmdSetScissorWithCount pfn_vkCmdSetScissorWithCount;
	extern PFN_vkCmdBindVertexBuffers2 pfn_vkCmdBindVertexBuffers2;
	extern PFN_vkCmdSetDepthTestEnable pfn_vkCmdSetDepthTestEnable;
	extern PFN_vkCmdSetDepthWriteEnable pfn_vkCmdSetDepthWriteEnable;
	extern PFN_vkCmdSetDepthCompareOp pfn_vkCmdSetDepthCompareOp;
	extern PFN_vkCmdSetDepthBoundsTestEnable pfn_vkCmdSetDepthBoundsTestEnable;
	extern PFN_vkCmdSetStencilTestEnable pfn_vkCmdSetStencilTestEnable;
	extern PFN_vkCmdSetStencilOp pfn_vkCmdSetStencilOp;
	extern PFN_vkCmdSetRasterizerDiscardEnable pfn_vkCmdSetRasterizerDiscardEnable;
	extern PFN_vkCmdSetDepthBiasEnable pfn_vkCmdSetDepthBiasEnable;
	extern PFN_vkCmdSetPrimitiveRestartEnable pfn_vkCmdSetPrimitiveRestartEnable;
	extern PFN_vkGetDeviceBufferMemoryRequirements pfn_vkGetDeviceBufferMemoryRequirements;
	extern PFN_vkGetDeviceImageMemoryRequirements pfn_vkGetDeviceImageMemoryRequirements;
	extern PFN_vkGetDeviceImageSparseMemoryRequirements pfn_vkGetDeviceImageSparseMemoryRequirements;

	// Vulkan 1.4
	/* extern PFN_vkCmdSetLineStipple pfn_vkCmdSetLineStipple;
	extern PFN_vkMapMemory2 pfn_vkMapMemory2;
	extern PFN_vkUnmapMemory2 pfn_vkUnmapMemory2;
	extern PFN_vkCmdBindIndexBuffer2 pfn_vkCmdBindIndexBuffer2;
	extern PFN_vkGetRenderingAreaGranularity pfn_vkGetRenderingAreaGranularity;
	extern PFN_vkGetDeviceImageSubresourceLayout pfn_vkGetDeviceImageSubresourceLayout;
	extern PFN_vkGetImageSubresourceLayout2 pfn_vkGetImageSubresourceLayout2;
	extern PFN_vkCmdPushDescriptorSet pfn_vkCmdPushDescriptorSet;
	extern PFN_vkCmdPushDescriptorSetWithTemplate pfn_vkCmdPushDescriptorSetWithTemplate;
	extern PFN_vkCmdSetRenderingAttachmentLocations pfn_vkCmdSetRenderingAttachmentLocations;
	extern PFN_vkCmdSetRenderingInputAttachmentIndices pfn_vkCmdSetRenderingInputAttachmentIndices;
	extern PFN_vkCmdBindDescriptorSets2 pfn_vkCmdBindDescriptorSets2;
	extern PFN_vkCmdPushConstants2 pfn_vkCmdPushConstants2;
	extern PFN_vkCmdPushDescriptorSet2 pfn_vkCmdPushDescriptorSet2;
	extern PFN_vkCmdPushDescriptorSetWithTemplate2 pfn_vkCmdPushDescriptorSetWithTemplate2;
	extern PFN_vkCopyMemoryToImage pfn_vkCopyMemoryToImage;
	extern PFN_vkCopyImageToMemory pfn_vkCopyImageToMemory;
	extern PFN_vkCopyImageToImage pfn_vkCopyImageToImage;
	extern PFN_vkTransitionImageLayout pfn_vkTransitionImageLayout; */

	// Debug Messages
	extern PFN_vkSetDebugUtilsObjectNameEXT pfn_vkSetDebugUtilsObjectNameEXT;
	extern PFN_vkSetDebugUtilsObjectTagEXT pfn_vkSetDebugUtilsObjectTagEXT;
	extern PFN_vkQueueBeginDebugUtilsLabelEXT pfn_vkQueueBeginDebugUtilsLabelEXT;
	extern PFN_vkQueueEndDebugUtilsLabelEXT pfn_vkQueueEndDebugUtilsLabelEXT;
	extern PFN_vkQueueInsertDebugUtilsLabelEXT pfn_vkQueueInsertDebugUtilsLabelEXT;
	extern PFN_vkCmdBeginDebugUtilsLabelEXT pfn_vkCmdBeginDebugUtilsLabelEXT;
	extern PFN_vkCmdEndDebugUtilsLabelEXT pfn_vkCmdEndDebugUtilsLabelEXT;
	extern PFN_vkCmdInsertDebugUtilsLabelEXT pfn_vkCmdInsertDebugUtilsLabelEXT;
	extern PFN_vkCreateDebugUtilsMessengerEXT pfn_vkCreateDebugUtilsMessengerEXT;
	extern PFN_vkDestroyDebugUtilsMessengerEXT pfn_vkDestroyDebugUtilsMessengerEXT;
	extern PFN_vkSubmitDebugUtilsMessageEXT pfn_vkSubmitDebugUtilsMessageEXT;

	// Surface
	extern PFN_vkDestroySurfaceKHR pfn_vkDestroySurfaceKHR;
	extern PFN_vkGetPhysicalDeviceSurfaceSupportKHR pfn_vkGetPhysicalDeviceSurfaceSupportKHR;
	extern PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR pfn_vkGetPhysicalDeviceSurfaceCapabilitiesKHR;
	extern PFN_vkGetPhysicalDeviceSurfaceFormatsKHR pfn_vkGetPhysicalDeviceSurfaceFormatsKHR;
	extern PFN_vkGetPhysicalDeviceSurfacePresentModesKHR pfn_vkGetPhysicalDeviceSurfacePresentModesKHR;

	// Swapchain
	extern PFN_vkCreateSwapchainKHR pfn_vkCreateSwapchainKHR;
	extern PFN_vkDestroySwapchainKHR pfn_vkDestroySwapchainKHR;
	extern PFN_vkGetSwapchainImagesKHR pfn_vkGetSwapchainImagesKHR;
	extern PFN_vkAcquireNextImageKHR pfn_vkAcquireNextImageKHR;
	extern PFN_vkQueuePresentKHR pfn_vkQueuePresentKHR;
	extern PFN_vkGetDeviceGroupPresentCapabilitiesKHR pfn_vkGetDeviceGroupPresentCapabilitiesKHR;
	extern PFN_vkGetDeviceGroupSurfacePresentModesKHR pfn_vkGetDeviceGroupSurfacePresentModesKHR;
	extern PFN_vkGetPhysicalDevicePresentRectanglesKHR pfn_vkGetPhysicalDevicePresentRectanglesKHR;
	extern PFN_vkAcquireNextImage2KHR pfn_vkAcquireNextImage2KHR;

#ifdef RE_OS_WINDOWS
	// Win32-Surface
	extern PFN_vkCreateWin32SurfaceKHR pfn_vkCreateWin32SurfaceKHR;
	extern PFN_vkGetPhysicalDeviceWin32PresentationSupportKHR pfn_vkGetPhysicalDeviceWin32PresentationSupportKHR;
#elif defined RE_OS_LINUX
	// Wayland-Surface
	extern PFN_vkCreateWaylandSurfaceKHR pfn_vkCreateWaylandSurfaceKHR;
	extern PFN_vkGetPhysicalDeviceWaylandPresentationSupportKHR pfn_vkGetPhysicalDeviceWaylandPresentationSupportKHR;
	// X11-Surface
	extern PFN_vkCreateXlibSurfaceKHR pfn_vkCreateXlibSurfaceKHR;
	extern PFN_vkGetPhysicalDeviceXlibPresentationSupportKHR pfn_vkGetPhysicalDeviceXlibPresentationSupportKHR;
#endif /* RE_OS_WINDOWS, RE_OS_LINUX */

	bool link_vulkan();
	void unlink_vulkan();

	bool check_vulkan_result(VkResult vk_eResult, const char* pcFile, const char* pcFunc, uint32_t u32Line);
#define CHECK_VK_RESULT(T) ([&](const char *const pcActualFunc) -> bool { \
			add_to_stack_trace(__FILE__, pcActualFunc, __LINE__, "\0"); \
			const bool bResult = check_vulkan_result(T, __FILE__, pcActualFunc, __LINE__); \
			remove_from_stack_trace(); \
			return bResult; \
		})(__func__)

// Vulkan 1.0
#define vkCreateInstance pfn_vkCreateInstance
#define vkDestroyInstance pfn_vkDestroyInstance
#define vkEnumeratePhysicalDevices pfn_vkEnumeratePhysicalDevices
#define vkGetPhysicalDeviceFeatures pfn_vkGetPhysicalDeviceFeatures
#define vkGetPhysicalDeviceFormatProperties pfn_vkGetPhysicalDeviceFormatProperties
#define vkGetPhysicalDeviceImageFormatProperties pfn_vkGetPhysicalDeviceImageFormatProperties
#define vkGetPhysicalDeviceProperties pfn_vkGetPhysicalDeviceProperties
#define vkGetPhysicalDeviceQueueFamilyProperties pfn_vkGetPhysicalDeviceQueueFamilyProperties
#define vkGetPhysicalDeviceMemoryProperties pfn_vkGetPhysicalDeviceMemoryProperties
#define vkGetInstanceProcAddr pfn_vkGetInstanceProcAddr
#define vkGetDeviceProcAddr pfn_vkGetDeviceProcAddr
#define vkCreateDevice pfn_vkCreateDevice
#define vkDestroyDevice pfn_vkDestroyDevice
#define vkEnumerateInstanceExtensionProperties pfn_vkEnumerateInstanceExtensionProperties
#define vkEnumerateDeviceExtensionProperties pfn_vkEnumerateDeviceExtensionProperties
#define vkEnumerateInstanceLayerProperties pfn_vkEnumerateInstanceLayerProperties
#define vkEnumerateDeviceLayerProperties pfn_vkEnumerateDeviceLayerProperties
#define vkGetDeviceQueue pfn_vkGetDeviceQueue
#define vkQueueSubmit pfn_vkQueueSubmit
#define vkQueueWaitIdle pfn_vkQueueWaitIdle
#define vkDeviceWaitIdle pfn_vkDeviceWaitIdle
#define vkAllocateMemory pfn_vkAllocateMemory
#define vkFreeMemory pfn_vkFreeMemory
#define vkMapMemory pfn_vkMapMemory
#define vkUnmapMemory pfn_vkUnmapMemory
#define vkFlushMappedMemoryRanges pfn_vkFlushMappedMemoryRanges
#define vkInvalidateMappedMemoryRanges pfn_vkInvalidateMappedMemoryRanges
#define vkGetDeviceMemoryCommitment pfn_vkGetDeviceMemoryCommitment
#define vkBindBufferMemory pfn_vkBindBufferMemory
#define vkBindImageMemory pfn_vkBindImageMemory
#define vkGetBufferMemoryRequirements pfn_vkGetBufferMemoryRequirements
#define vkGetImageMemoryRequirements pfn_vkGetImageMemoryRequirements
#define vkGetImageSparseMemoryRequirements pfn_vkGetImageSparseMemoryRequirements
#define vkGetPhysicalDeviceSparseImageFormatProperties pfn_vkGetPhysicalDeviceSparseImageFormatProperties
#define vkQueueBindSparse pfn_vkQueueBindSparse
#define vkCreateFence pfn_vkCreateFence
#define vkDestroyFence pfn_vkDestroyFence
#define vkResetFences pfn_vkResetFences
#define vkGetFenceStatus pfn_vkGetFenceStatus
#define vkWaitForFences pfn_vkWaitForFences
#define vkCreateSemaphore pfn_vkCreateSemaphore
#define vkDestroySemaphore pfn_vkDestroySemaphore
#define vkCreateEvent pfn_vkCreateEvent
#define vkDestroyEvent pfn_vkDestroyEvent
#define vkGetEventStatus pfn_vkGetEventStatus
#define vkSetEvent pfn_vkSetEvent
#define vkResetEvent pfn_vkResetEvent
#define vkCreateQueryPool pfn_vkCreateQueryPool
#define vkDestroyQueryPool pfn_vkDestroyQueryPool
#define vkGetQueryPoolResults pfn_vkGetQueryPoolResults
#define vkCreateBuffer pfn_vkCreateBuffer
#define vkDestroyBuffer pfn_vkDestroyBuffer
#define vkCreateBufferView pfn_vkCreateBufferView
#define vkDestroyBufferView pfn_vkDestroyBufferView
#define vkCreateImage pfn_vkCreateImage
#define vkDestroyImage pfn_vkDestroyImage
#define vkGetImageSubresourceLayout pfn_vkGetImageSubresourceLayout
#define vkCreateImageView pfn_vkCreateImageView
#define vkDestroyImageView pfn_vkDestroyImageView
#define vkCreateShaderModule pfn_vkCreateShaderModule
#define vkDestroyShaderModule pfn_vkDestroyShaderModule
#define vkCreatePipelineCache pfn_vkCreatePipelineCache
#define vkDestroyPipelineCache pfn_vkDestroyPipelineCache
#define vkGetPipelineCacheData pfn_vkGetPipelineCacheData
#define vkMergePipelineCaches pfn_vkMergePipelineCaches
#define vkCreateGraphicsPipelines pfn_vkCreateGraphicsPipelines
#define vkCreateComputePipelines pfn_vkCreateComputePipelines
#define vkDestroyPipeline pfn_vkDestroyPipeline
#define vkCreatePipelineLayout pfn_vkCreatePipelineLayout
#define vkDestroyPipelineLayout pfn_vkDestroyPipelineLayout
#define vkCreateSampler pfn_vkCreateSampler
#define vkDestroySampler pfn_vkDestroySampler
#define vkCreateDescriptorSetLayout pfn_vkCreateDescriptorSetLayout
#define vkDestroyDescriptorSetLayout pfn_vkDestroyDescriptorSetLayout
#define vkCreateDescriptorPool pfn_vkCreateDescriptorPool
#define vkDestroyDescriptorPool pfn_vkDestroyDescriptorPool
#define vkResetDescriptorPool pfn_vkResetDescriptorPool
#define vkAllocateDescriptorSets pfn_vkAllocateDescriptorSets
#define vkFreeDescriptorSets pfn_vkFreeDescriptorSets
#define vkUpdateDescriptorSets pfn_vkUpdateDescriptorSets
#define vkCreateFramebuffer pfn_vkCreateFramebuffer
#define vkDestroyFramebuffer pfn_vkDestroyFramebuffer
#define vkCreateRenderPass pfn_vkCreateRenderPass
#define vkDestroyRenderPass pfn_vkDestroyRenderPass
#define vkGetRenderAreaGranularity pfn_vkGetRenderAreaGranularity
#define vkCreateCommandPool pfn_vkCreateCommandPool
#define vkDestroyCommandPool pfn_vkDestroyCommandPool
#define vkResetCommandPool pfn_vkResetCommandPool
#define vkAllocateCommandBuffers pfn_vkAllocateCommandBuffers
#define vkFreeCommandBuffers pfn_vkFreeCommandBuffers
#define vkBeginCommandBuffer pfn_vkBeginCommandBuffer
#define vkEndCommandBuffer pfn_vkEndCommandBuffer
#define vkResetCommandBuffer pfn_vkResetCommandBuffer
#define vkCmdBindPipeline pfn_vkCmdBindPipeline
#define vkCmdSetViewport pfn_vkCmdSetViewport
#define vkCmdSetScissor pfn_vkCmdSetScissor
#define vkCmdSetLineWidth pfn_vkCmdSetLineWidth
#define vkCmdSetDepthBias pfn_vkCmdSetDepthBias
#define vkCmdSetBlendConstants pfn_vkCmdSetBlendConstants
#define vkCmdSetDepthBounds pfn_vkCmdSetDepthBounds
#define vkCmdSetStencilCompareMask pfn_vkCmdSetStencilCompareMask
#define vkCmdSetStencilWriteMask pfn_vkCmdSetStencilWriteMask
#define vkCmdSetStencilReference pfn_vkCmdSetStencilReference
#define vkCmdBindDescriptorSets pfn_vkCmdBindDescriptorSets
#define vkCmdBindIndexBuffer pfn_vkCmdBindIndexBuffer
#define vkCmdBindVertexBuffers pfn_vkCmdBindVertexBuffers
#define vkCmdDraw pfn_vkCmdDraw
#define vkCmdDrawIndexed pfn_vkCmdDrawIndexed
#define vkCmdDrawIndirect pfn_vkCmdDrawIndirect
#define vkCmdDrawIndexedIndirect pfn_vkCmdDrawIndexedIndirect
#define vkCmdDispatch pfn_vkCmdDispatch
#define vkCmdDispatchIndirect pfn_vkCmdDispatchIndirect
#define vkCmdCopyBuffer pfn_vkCmdCopyBuffer
#define vkCmdCopyImage pfn_vkCmdCopyImage
#define vkCmdBlitImage pfn_vkCmdBlitImage
#define vkCmdCopyBufferToImage pfn_vkCmdCopyBufferToImage
#define vkCmdCopyImageToBuffer pfn_vkCmdCopyImageToBuffer
#define vkCmdUpdateBuffer pfn_vkCmdUpdateBuffer
#define vkCmdFillBuffer pfn_vkCmdFillBuffer
#define vkCmdClearColorImage pfn_vkCmdClearColorImage
#define vkCmdClearDepthStencilImage pfn_vkCmdClearDepthStencilImage
#define vkCmdClearAttachments pfn_vkCmdClearAttachments
#define vkCmdResolveImage pfn_vkCmdResolveImage
#define vkCmdSetEvent pfn_vkCmdSetEvent
#define vkCmdResetEvent pfn_vkCmdResetEvent
#define vkCmdWaitEvents pfn_vkCmdWaitEvents
#define vkCmdPipelineBarrier pfn_vkCmdPipelineBarrier
#define vkCmdBeginQuery pfn_vkCmdBeginQuery
#define vkCmdEndQuery pfn_vkCmdEndQuery
#define vkCmdResetQueryPool pfn_vkCmdResetQueryPool
#define vkCmdWriteTimestamp pfn_vkCmdWriteTimestamp
#define vkCmdCopyQueryPoolResults pfn_vkCmdCopyQueryPoolResults
#define vkCmdPushConstants pfn_vkCmdPushConstants
#define vkCmdBeginRenderPass pfn_vkCmdBeginRenderPass
#define vkCmdNextSubpass pfn_vkCmdNextSubpass
#define vkCmdEndRenderPass pfn_vkCmdEndRenderPass
#define vkCmdExecuteCommands pfn_vkCmdExecuteCommands

// Vulkan 1.1
#define vkEnumerateInstanceVersion pfn_vkEnumerateInstanceVersion
#define vkBindBufferMemory2 pfn_vkBindBufferMemory2
#define vkBindImageMemory2 pfn_vkBindImageMemory2
#define vkGetDeviceGroupPeerMemoryFeatures pfn_vkGetDeviceGroupPeerMemoryFeatures
#define vkCmdSetDeviceMask pfn_vkCmdSetDeviceMask
#define vkCmdDispatchBase pfn_vkCmdDispatchBase
#define vkEnumeratePhysicalDeviceGroups pfn_vkEnumeratePhysicalDeviceGroups
#define vkGetImageMemoryRequirements2 pfn_vkGetImageMemoryRequirements2
#define vkGetBufferMemoryRequirements2 pfn_vkGetBufferMemoryRequirements2
#define vkGetImageSparseMemoryRequirements2 pfn_vkGetImageSparseMemoryRequirements2
#define vkGetPhysicalDeviceFeatures2 pfn_vkGetPhysicalDeviceFeatures2
#define vkGetPhysicalDeviceProperties2 pfn_vkGetPhysicalDeviceProperties2
#define vkGetPhysicalDeviceFormatProperties2 pfn_vkGetPhysicalDeviceFormatProperties2
#define vkGetPhysicalDeviceImageFormatProperties2 pfn_vkGetPhysicalDeviceImageFormatProperties2
#define vkGetPhysicalDeviceQueueFamilyProperties2 pfn_vkGetPhysicalDeviceQueueFamilyProperties2
#define vkGetPhysicalDeviceMemoryProperties2 pfn_vkGetPhysicalDeviceMemoryProperties2
#define vkGetPhysicalDeviceSparseImageFormatProperties2 pfn_vkGetPhysicalDeviceSparseImageFormatProperties2
#define vkTrimCommandPool pfn_vkTrimCommandPool
#define vkGetDeviceQueue2 pfn_vkGetDeviceQueue2
#define vkCreateSamplerYcbcrConversion pfn_vkCreateSamplerYcbcrConversion
#define vkDestroySamplerYcbcrConversion pfn_vkDestroySamplerYcbcrConversion
#define vkCreateDescriptorUpdateTemplate pfn_vkCreateDescriptorUpdateTemplate
#define vkDestroyDescriptorUpdateTemplate pfn_vkDestroyDescriptorUpdateTemplate
#define vkUpdateDescriptorSetWithTemplate pfn_vkUpdateDescriptorSetWithTemplate
#define vkGetPhysicalDeviceExternalBufferProperties pfn_vkGetPhysicalDeviceExternalBufferProperties
#define vkGetPhysicalDeviceExternalFenceProperties pfn_vkGetPhysicalDeviceExternalFenceProperties
#define vkGetPhysicalDeviceExternalSemaphoreProperties pfn_vkGetPhysicalDeviceExternalSemaphoreProperties
#define vkGetDescriptorSetLayoutSupport pfn_vkGetDescriptorSetLayoutSupport

// Vulkan 1.2
#define vkCmdDrawIndirectCount pfn_vkCmdDrawIndirectCount
#define vkCmdDrawIndexedIndirectCount pfn_vkCmdDrawIndexedIndirectCount
#define vkCreateRenderPass2 pfn_vkCreateRenderPass2
#define vkCmdBeginRenderPass2 pfn_vkCmdBeginRenderPass2
#define vkCmdNextSubpass2 pfn_vkCmdNextSubpass2
#define vkCmdEndRenderPass2 pfn_vkCmdEndRenderPass2
#define vkResetQueryPool pfn_vkResetQueryPool
#define vkGetSemaphoreCounterValue pfn_vkGetSemaphoreCounterValue
#define vkWaitSemaphores pfn_vkWaitSemaphores
#define vkSignalSemaphore pfn_vkSignalSemaphore
#define vkGetBufferDeviceAddress pfn_vkGetBufferDeviceAddress
#define vkGetBufferOpaqueCaptureAddress pfn_vkGetBufferOpaqueCaptureAddress
#define vkGetDeviceMemoryOpaqueCaptureAddress pfn_vkGetDeviceMemoryOpaqueCaptureAddress

// Vulkan 1.3
#define vkGetPhysicalDeviceToolProperties pfn_vkGetPhysicalDeviceToolProperties
#define vkCreatePrivateDataSlot pfn_vkCreatePrivateDataSlot
#define vkDestroyPrivateDataSlot pfn_vkDestroyPrivateDataSlot
#define vkSetPrivateData pfn_vkSetPrivateData
#define vkGetPrivateData pfn_vkGetPrivateData
#define vkCmdSetEvent2 pfn_vkCmdSetEvent2
#define vkCmdResetEvent2 pfn_vkCmdResetEvent2
#define vkCmdWaitEvents2 pfn_vkCmdWaitEvents2
#define vkCmdPipelineBarrier2 pfn_vkCmdPipelineBarrier2
#define vkCmdWriteTimestamp2 pfn_vkCmdWriteTimestamp2
#define vkQueueSubmit2 pfn_vkQueueSubmit2
#define vkCmdCopyBuffer2 pfn_vkCmdCopyBuffer2
#define vkCmdCopyImage2 pfn_vkCmdCopyImage2
#define vkCmdCopyBufferToImage2 pfn_vkCmdCopyBufferToImage2
#define vkCmdCopyImageToBuffer2 pfn_vkCmdCopyImageToBuffer2
#define vkCmdBlitImage2 pfn_vkCmdBlitImage2
#define vkCmdResolveImage2 pfn_vkCmdResolveImage2
#define vkCmdBeginRendering pfn_vkCmdBeginRendering
#define vkCmdEndRendering pfn_vkCmdEndRendering
#define vkCmdSetCullMode pfn_vkCmdSetCullMode
#define vkCmdSetFrontFace pfn_vkCmdSetFrontFace
#define vkCmdSetPrimitiveTopology pfn_vkCmdSetPrimitiveTopology
#define vkCmdSetViewportWithCount pfn_vkCmdSetViewportWithCount
#define vkCmdSetScissorWithCount pfn_vkCmdSetScissorWithCount
#define vkCmdBindVertexBuffers2 pfn_vkCmdBindVertexBuffers2
#define vkCmdSetDepthTestEnable pfn_vkCmdSetDepthTestEnable
#define vkCmdSetDepthWriteEnable pfn_vkCmdSetDepthWriteEnable
#define vkCmdSetDepthCompareOp pfn_vkCmdSetDepthCompareOp
#define vkCmdSetDepthBoundsTestEnable pfn_vkCmdSetDepthBoundsTestEnable
#define vkCmdSetStencilTestEnable pfn_vkCmdSetStencilTestEnable
#define vkCmdSetStencilOp pfn_vkCmdSetStencilOp
#define vkCmdSetRasterizerDiscardEnable pfn_vkCmdSetRasterizerDiscardEnable
#define vkCmdSetDepthBiasEnable pfn_vkCmdSetDepthBiasEnable
#define vkCmdSetPrimitiveRestartEnable pfn_vkCmdSetPrimitiveRestartEnable
#define vkGetDeviceBufferMemoryRequirements pfn_vkGetDeviceBufferMemoryRequirements
#define vkGetDeviceImageMemoryRequirements pfn_vkGetDeviceImageMemoryRequirements
#define vkGetDeviceImageSparseMemoryRequirements pfn_vkGetDeviceImageSparseMemoryRequirements

// Vulkan 1.4
/* #define vkCmdSetLineStipple pfn_vkCmdSetLineStipple
#define vkMapMemory2 pfn_vkMapMemory2
#define vkUnmapMemory2 pfn_vkUnmapMemory2
#define vkCmdBindIndexBuffer2 pfn_vkCmdBindIndexBuffer2
#define vkGetRenderingAreaGranularity pfn_vkGetRenderingAreaGranularity
#define vkGetDeviceImageSubresourceLayout pfn_vkGetDeviceImageSubresourceLayout
#define vkGetImageSubresourceLayout2 pfn_vkGetImageSubresourceLayout2
#define vkCmdPushDescriptorSet pfn_vkCmdPushDescriptorSet
#define vkCmdPushDescriptorSetWithTemplate pfn_vkCmdPushDescriptorSetWithTemplate
#define vkCmdSetRenderingAttachmentLocations pfn_vkCmdSetRenderingAttachmentLocations
#define vkCmdSetRenderingInputAttachmentIndices pfn_vkCmdSetRenderingInputAttachmentIndices
#define vkCmdBindDescriptorSets2 pfn_vkCmdBindDescriptorSets2
#define vkCmdPushConstants2 pfn_vkCmdPushConstants2
#define vkCmdPushDescriptorSet2 pfn_vkCmdPushDescriptorSet2
#define vkCmdPushDescriptorSetWithTemplate2 pfn_vkCmdPushDescriptorSetWithTemplate2
#define vkCopyMemoryToImage pfn_vkCopyMemoryToImage
#define vkCopyImageToMemory pfn_vkCopyImageToMemory
#define vkCopyImageToImage pfn_vkCopyImageToImage
#define vkTransitionImageLayout pfn_vkTransitionImageLayout */

// Debug Messages
#define vkSetDebugUtilsObjectNameEXT pfn_vkSetDebugUtilsObjectNameEXT;
#define vkSetDebugUtilsObjectTagEXT pfn_vkSetDebugUtilsObjectTagEXT;
#define vkQueueBeginDebugUtilsLabelEXT pfn_vkQueueBeginDebugUtilsLabelEXT;
#define vkQueueEndDebugUtilsLabelEXT pfn_vkQueueEndDebugUtilsLabelEXT;
#define vkQueueInsertDebugUtilsLabelEXT pfn_vkQueueInsertDebugUtilsLabelEXT;
#define vkCmdBeginDebugUtilsLabelEXT pfn_vkCmdBeginDebugUtilsLabelEXT;
#define vkCmdEndDebugUtilsLabelEXT pfn_vkCmdEndDebugUtilsLabelEXT;
#define vkCmdInsertDebugUtilsLabelEXT pfn_vkCmdInsertDebugUtilsLabelEXT;
#define vkCreateDebugUtilsMessengerEXT pfn_vkCreateDebugUtilsMessengerEXT;
#define vkDestroyDebugUtilsMessengerEXT pfn_vkDestroyDebugUtilsMessengerEXT;
#define vkSubmitDebugUtilsMessageEXT pfn_vkSubmitDebugUtilsMessageEXT;

// Surface
#define vkDestroySurfaceKHR pfn_vkDestroySurfaceKHR
#define vkGetPhysicalDeviceSurfaceSupportKHR pfn_vkGetPhysicalDeviceSurfaceSupportKHR
#define vkGetPhysicalDeviceSurfaceCapabilitiesKHR pfn_vkGetPhysicalDeviceSurfaceCapabilitiesKHR
#define vkGetPhysicalDeviceSurfaceFormatsKHR pfn_vkGetPhysicalDeviceSurfaceFormatsKHR
#define vkGetPhysicalDeviceSurfacePresentModesKHR pfn_vkGetPhysicalDeviceSurfacePresentModesKHR

// Swapchain
#define vkCreateSwapchainKHR pfn_vkCreateSwapchainKHR
#define vkDestroySwapchainKHR pfn_vkDestroySwapchainKHR
#define vkGetSwapchainImagesKHR pfn_vkGetSwapchainImagesKHR
#define vkAcquireNextImageKHR pfn_vkAcquireNextImageKHR
#define vkQueuePresentKHR pfn_vkQueuePresentKHR
#define vkGetDeviceGroupPresentCapabilitiesKHR pfn_vkGetDeviceGroupPresentCapabilitiesKHR
#define vkGetDeviceGroupSurfacePresentModesKHR pfn_vkGetDeviceGroupSurfacePresentModesKHR
#define vkGetPhysicalDevicePresentRectanglesKHR pfn_vkGetPhysicalDevicePresentRectanglesKHR
#define vkAcquireNextImage2KHR pfn_vkAcquireNextImage2KHR

#ifdef RE_OS_WINDOWS
# define vkCreateWin32SurfaceKHR pfn_vkCreateWin32SurfaceKHR
# define vkGetPhysicalDeviceWin32PresentationSupportKHR pfn_vkGetPhysicalDeviceWin32PresentationSupportKHR
#elif defined RE_OS_LINUX
# define vkCreateWaylandSurfaceKHR pfn_vkCreateWaylandSurfaceKHR
# define vkGetPhysicalDeviceWaylandPresentationSupportKHR pfn_vkGetPhysicalDeviceWaylandPresentationSupportKHR
# define vkCreateXlibSurfaceKHR pfn_vkCreateXlibSurfaceKHR
# define vkGetPhysicalDeviceXlibPresentationSupportKHR pfn_vkGetPhysicalDeviceXlibPresentationSupportKHR
#endif /* RE_OS_WINDOWS, RE_OS_LINUX */

#define VK_KHR_VALIDATION_LAYER_NAME "VK_LAYER_KHRONOS_validation"

}

#include "RE_Vulkan_Wrapper Functions.hpp"
#include "RE_Vulkan_Wrapper Classes.hpp"

#endif /* __RE_VULKAN_H__ */
